var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"A developer observes that an Apex test method fails in the Sandbox. To identify the issue, thedeveloper copies the code inside the test method and executes it via the Execute Anonymous tool inthe Developer Console. The code then executes with no exceptions or errors. Why did the testmethod fail in the sandbox and pass in the Developer Console?", "choice":["The test method has a syntax error in the code.","The test method relies on existing data in the sandbox.","The test method is calling an @future method.","The test method does not use System.runAs to execute as a specific user."], "answer":["The test method relies on existing data in the sandbox."] , "feedback_tf":["", ""]}
,{ "question":"Which code in a Visualforce page and/or controller might present a security vulnerability?", "choice":["＜apex:outputField value= {!ctrl.userInput}  /＞","＜apex:outputText escape= false  value=  {!$CurrentPage.parameters.userInput}  /＞","＜apex:outputText value= {!$CurrentPage.parameters.userInput}  /＞","＜apex:outputField escape= false  value= {!ctrl.userInput}  /＞"], "answer":["＜apex:outputText escape= false  value=  {!$CurrentPage.parameters.userInput}  /＞"] , "feedback_tf":["", ""]}
,{ "question":"What are two ways a developer can get the status of an enquered job for a class thatqueueable interface?Choose 2 answers", "choice":["View the apex status Page","View the apex flex Queue","View the apex Jobs page (Missed)","Query the AsyncApexJobe object (Missed)"], "answer":["View the apex Jobs page (Missed)","Query the AsyncApexJobe object (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"The Sales Management team hires a new intern. The intern is not allowed to viewOpportunities, but needs to see the Most Recent Closed Date of all child Opportunities when viewingan Account record. What would a developer do to meet this requirement?", "choice":["Create a trigger on the Account object that queries the Close Date of the most recentOpportunities.","Create a Workflow rule on the Opportunity object that updates a field on the parent Account.","Create a formula field on the Account object that performs a MAX on the Opportunity Close Datefield.","Create a roll-up summary field on the Account object that performs a MAX on the OpportunityClose Date field."], "answer":["Create a roll-up summary field on the Account object that performs a MAX on the OpportunityClose Date field."] , "feedback_tf":["", ""]}
,{ "question":"A developer is creating an enhancement to an application that will allow people to be relatedto their employer.Which data model provides the simplest solution to meet the requirements?", "choice":["Create a lookup realtionship to indicate that a person has an employer","Create a master-detail relationship to indicate that a person has an employer","Create a junction object to relate many people to many through master-detail relationship","Create a junction object to relate many people to many through lookup relationship"], "answer":["Create a master-detail relationship to indicate that a person has an employer"] , "feedback_tf":["", ""]}
,{ "question":"What is the result of the debug statements in testMethod3 when you create test data usingtestSetup in below code?", "choice":["Account0.Phone=333-8781, Account1.Phone=333-8780","Account0.Phone=888-1515, Account1.Phone=999-2525","Account0.Phone=333-8780, Account1.Phone=333-8781","Account0.Phone=888-1515, Account1.Phone=999-1515"], "answer":["Account0.Phone=333-8780, Account1.Phone=333-8781"] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of using an after insert trigger over using a before insert trigger?", "choice":["An after insert trigger allows a developer to bypass validation rules when updating fields on thenew record.","An after insert trigger allows a developer to insert other objects that reference the new record.","An after insert trigger allows a developer to make a callout to an external service.","An after insert trigger allows a developer to modify fields in the new record without a query."], "answer":["An after insert trigger allows a developer to insert other objects that reference the new record."] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of using an after insert trigger over using a before insert trigger?", "choice":["An after insert trigger allows a developer to bypass validation rules when updating fields on thenew record.","An after insert trigger allows a developer to insert other objects that reference the new record.","An after insert trigger allows a developer to make a callout to an external service.","An after insert trigger allows a developer to modify fields in the new record without a query."], "answer":["An after insert trigger allows a developer to insert other objects that reference the new record."] , "feedback_tf":["", ""]}
,{ "question":"An Apex transaction inserts 100 Account records and 2,000 Contact records beforeencountering a DML exception when attempting to insert 500 Opportunity records. The Accountrecords are inserted by calling the database.insert() method with the allOrNone argument set tofalse. The Contact and Opportunity records are inserted using the standalone insert statement. Howmany total records will be committed to the database in this transaction?", "choice":["100","2000","2100","0"], "answer":["100"] , "feedback_tf":["", ""]}
,{ "question":"Which set of roll-up types are available when creating a roll-up summary field?", "choice":["COUNT, SUM, MIN, MAX","AVERAGE, SUM, MIN, MAX","SUM, MIN, MAX","AVRAGE, COUNT, SUM, MIN, MAX"], "answer":["COUNT, SUM, MIN, MAX"] , "feedback_tf":["", ""]}
]}
