var config = {"settings": {"add_css_file":false , "add_js_file":false , "custom_lang":false , "head_write_js":"" , "head_write_css":"" , "format":"table" , "messages":{"intro":"Salesforce 認定デベロッパー 練習問題"}} ,"questions":[
{"question": "以下の要件があります。開発者はどのイベントのケーストリガーを作成すべきですか？（2つ選択）関連する取引先の値に基づき、ケース項目「KeyPerson__c」に値を設定する。" ,"choice":["Before Update" ,"After Insert" ,"Before Insert" ,"After Update"] ,"answer":["Before Update" ,"Before Insert"] ,"feedback_tf":["" ,""]}
, {"question": "トリガのカスケード実行（連鎖実行）について正しい記述はどれか（1つ選択）" ,"choice":["トリガのカスケード実行により例外が発生する" ,"カスケード実行トリガも、同じ実行コンテキストで動作しガバナ制限を共有する" ,"各トリガーは新しい実行コンテキストを開始します" ,"カスケード実行できるトリガーは5つまでとの制限がある"] ,"answer":["カスケード実行トリガも、同じ実行コンテキストで動作しガバナ制限を共有する"] ,"feedback_tf":["" ,""]}
, {"question": "下記の中で、Before Updateトリガでは実行できないアクションはどれか（2つ選択）" ,"choice":["Trigger.newを使い項目の値を変更する" ,"Trigger.old の値を修正する" ,"値の変更を受け入れる前に、入力チェックを行う" ,"レコードの変更を回避するため、Trigger.new を削除する"] ,"answer":["Trigger.old の値を修正する" ,"レコードの変更を回避するため、Trigger.new を削除する"] ,"feedback_tf":["" ,""]}
, {"question": "既存の「契約」を更新する為、以下の「商談」トリガがある。「商談」を2,000件読み込んだ場合、「契約」は何件更新される？（１つ選択）<pre><br>List<Contract> getContracts = new List<Contract>();<br>for(Opportunity opp: (List<Opportunity>) Trigger.New) {<br>	Contract con = [SELECT Id FROM Contract WHERE Id =: opp.ContractId];<br>	con.Description = ‘This is the contract for Opportunity ‘ + opp.Name;<br>	getContracts.add(con);<br>}<br>update getContracts;<br></pre>" ,"choice":["2,000" ,"100" ,"1" ,"0"] ,"answer":["0"] ,"feedback_tf":["" ,""]}
, {"question": "Apexトリガを書くとき、何を考慮しておく必要がある？（２つ選択）" ,"choice":["オブジェクト毎に、Apexトリガは一つにする必要がある" ,"Apexトリガにはロジックを書かず、Handlerクラスに移譲する" ,"Apexトリガは他のトリガを起動すべきでない" ,"ApexトリガはDML実行時に@futureアノテーションを付けるべき"] ,"answer":["オブジェクト毎に、Apexトリガは一つにする必要がある" ,"Apexトリガにはロジックを書かず、Handlerクラスに移譲する"] ,"feedback_tf":["" ,""]}
, {"question": "次のコードのうち、ループ文に含めてはいけないのは？（２つ選択）" ,"choice":["insert accountList;" ,"System.debug(‘The following account has been updated’ + ‘acc.Id ‘);" ,"Opportunity getOpp = [SELECT Id, AccountId FROM Opportunity WHERE AccountId =: acc.Id];" ,"if(acc.NumberOfEmployees > 5000){"] ,"answer":["insert accountList;" ,"Opportunity getOpp = [SELECT Id, AccountId FROM Opportunity WHERE AccountId =: acc.Id];"] ,"feedback_tf":["" ,""]}
, {"question": "以下の標準オブジェクトの内、DML操作のサポート外なのはどれ？（２つ選択）" ,"choice":["プロファイル" ,"ユーザー" ,"ケース" ,"レコードタイプ"] ,"answer":["プロファイル" ,"レコードタイプ"] ,"feedback_tf":["" ,""]}
, {"question": "検索結果に含める情報を指定するにはSOSL文に何句を追加する？（１つ選択）" ,"choice":["LIMIT n" ,"RETURNING" ,"OFFSET n" ,"ORDER BY"] ,"answer":["RETURNING"] ,"feedback_tf":["" ,""]}
, {"question": "下記SOSL文の検索結果で、取引先60件が抽出される想定だったが、実際は取引先20件。SOSLのLIMIT指定について正しい記述は？（１つ選択）<pre><br>FIND {test} RETURNING Account(id), Contact, Opportunity LIMIT 60<br></pre>" ,"choice":["SOSLクエリではLIMIT指定ができない" ,"検索結果が戻ってきたオブジェクトで均等に分割された" ,"LIMITはオブジェクト毎に個別指定しなければならない" ,"上記SOSLは構文が正しくない"] ,"answer":["検索結果が戻ってきたオブジェクトで均等に分割された"] ,"feedback_tf":["" ,""]}
, {"question": "次のDML文のうち、エラーでないレコードだけ挿入できるのはどれ？（１つ選択）" ,"choice":["insert sObjectsToCreate;" ,"upsert sObjectsToCreate;" ,"Database.insert(sObjectsToCreate,true);" ,"Database.insert(sObjectsToCreate,false);"] ,"answer":["Database.insert(sObjectsToCreate,false);"] ,"feedback_tf":["" ,""]}
, {"question": "Visualforceページで、カスタムコントローラを使用する適切な例はどれ？（２つ選択）" ,"choice":["標準コントローラの編集アクションを上書きする必要がある時" ,"Visualforceページをシステムモードで実行する必要がある時" ,"Visualforceページで、標準コントローラの機能を置き換える必要がある時" ,"Visualforceページで、標準コントローラの保存アクションを上書きする必要がある時"] ,"answer":["Visualforceページをシステムモードで実行する必要がある時" ,"Visualforceページで、標準コントローラの機能を置き換える必要がある時"] ,"feedback_tf":["" ,""]}
, {"question": "Visualforceページで、コントローラ拡張を使用する適切な例はどれ？（３つ選択）" ,"choice":["標準コントローラの編集アクションを上書きする必要がある時" ,"新しいアクションを追加する必要がある時" ,"標準コントローラの機能を置き換える必要がある時" ,"Visualforceページをユーザモードで動作させる必要がある時"] ,"answer":["標準コントローラの編集アクションを上書きする必要がある時" ,"新しいアクションを追加する必要がある時" ,"Visualforceページをユーザモードで動作させる必要がある時"] ,"feedback_tf":["" ,""]}
, {"question": "カスタムコントローラでの「transient」キーワード使用について誤った記述はどれ？（１つ選択）" ,"choice":["「transient」キーワードは、VisualforceページのViewStateとして送信されず、保存しない一時変数を宣言する時に使う" ,"「transient」として変数宣言すると、ViewStateのサイズは増える" ,"「transient」キーワードはserializableなクラスでのみ使用できる" ,"「transient」キーワードは、Visualforceページで、ページ要求の間でのみ必要な項目に使用する"] ,"answer":["「transient」として変数宣言すると、ViewStateのサイズは増える"] ,"feedback_tf":["" ,""]}
, {"question": "Forループ内でのSOQL実行を回避するベストプラクティスについて間違いはどれ？（１つ選択）" ,"choice":["Forループの外側にSOQLクエリを移動すると、処理が早くなりガバナ制限に抵触する可能性も低くなる" ,"Forループの内側にSOQLクエリがあると、ループ毎にクエリ実行され、ガバナ制限に簡単に抵触してしまう" ,"以下のコードは正しくない for(Account a : [Select Id, Name From Account Limit 1000]){" ,"SOQL実行が必要な場合、一度の実行で必要なデータをまとめて取得し、取得結果を反復処理する必要がある"] ,"answer":["以下のコードは正しくない for(Account a : [Select Id, Name From Account Limit 1000]){"] ,"feedback_tf":["" ,""]}
, {"question": "futureメソッドについて正しい記述はどれ？（２つ選択）" ,"choice":["@futureアノテーション付きメソッドは、非同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドは、同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドから、別の@futureアノテーション付きメソッドを呼び出すことが出来る" ,"@futureアノテーション付きメソッドの戻り値は「void」しか選べない"] ,"answer":["@futureアノテーション付きメソッドは、非同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドの戻り値は「void」しか選べない"] ,"feedback_tf":["" ,""]}
, {"question": "Visualforceページで表示する項目について、ユーザが読み取りアクセス可能かどうやってチェックする？（１つ選択）" ,"choice":["Schema.DescribeFieldResultクラスのisAccessible()メソッドを呼ぶ" ,"Schema.DescribeFieldResultクラスのisViewable()メソッドを呼ぶ" ,"Schema.SObjectResultクラスのisReadable()メソッドを呼ぶ" ,"Schema.DescribeSObjectResultクラスのisAccessible()メソッドを呼ぶ"] ,"answer":["Schema.DescribeFieldResultクラスのisAccessible()メソッドを呼ぶ"] ,"feedback_tf":["" ,""]}
, {"question": "プログラムから共有設定にアクセスする事に関し、正しい記述はどれ？（３つ選択）" ,"choice":["取引先オブジェクトの共有オブジェクトは「AccountShare」である。" ,"取引先オブジェクトの共有オブジェクトは「Account__Share」である。" ,"カスタムオブジェクトの共有オブジェクトは「 CustomObject__Share 」である。" ,"主従関係の従側オブジェクトには、共有オブジェクトがない。"] ,"answer":["取引先オブジェクトの共有オブジェクトは「AccountShare」である。" ,"カスタムオブジェクトの共有オブジェクトは「 CustomObject__Share 」である。" ,"主従関係の従側オブジェクトには、共有オブジェクトがない。"] ,"feedback_tf":["" ,""]}
, {"question": "■スクラッチ組織を作成するために何を使用すべきですか。" ,"choice":["Developer Console" ,"Salesforce CLI" ,"Workbench" ,"Sandbox refresh"] ,"answer":["Salesforce CLI"] ,"feedback_tf":["" ,""]}
, {"question": "■VisualforceページのコンテンツをPDFとして表示するコードはどれですか" ,"choice":["<apex:page contentType=pdf>" ,"<apex:page rendersAs=application/pdf>" ,"<apex:page contentType=application/pdf>" ,"<apex:page renderAs=pdf>"] ,"answer":["<apex:page renderAs=pdf>"] ,"feedback_tf":["" ,""]}
, {"question": "■下記のコード、Xの実行結果：<pre><br>Boolean isOK;<br>Integer x;<br>String theString = ‘Hello’<br>if(isOK==false && itheString==‘Hello’ ;){<br>X=1;<br>}elseif(isOK=true && itheString==‘Hello’ ;){<br>X=2;<br>}elseif(isOK!=null && itheString==‘Hello’ ;){<br>X=3;<br>)elseif{<br>X=4;}<br></pre>" ,"choice":["1" ,"2" ,"3" ,"4"] ,"answer":["4"] ,"feedback_tf":["" ,""]}
, {"question": "■アプリケーションイベントは、従来のパブリッシュ/サブスクライブモデルに従い、イベントを発生させるためにどの方法が使用すべき" ,"choice":["Fire（）？" ,"Emit（）" ,"FireEvent（）"] ,"answer":["Fire（）？"] ,"feedback_tf":["" ,""]}
, {"question": "■開発者はテストクラスのすべてのメソッドのレコードを作成するには、どのメソッドアノテーションを使用する必要がありますか？" ,"choice":["@BeforeTest" ,"@isTest(SeeAllData=True)" ,"@TestSetup" ,"@PreTest"] ,"answer":["@TestSetup"] ,"feedback_tf":["" ,""]}
, {"question": "■開発者はユーザーがSalesforceに最後にログインした日時を確認できるのは、どのSalesforce機能ですか？リアルタイムの通知が必要ない" ,"choice":["開発者ログ" ,"イベント監視ログ" ,"カレンダーイベント"] ,"answer":["イベント監視ログ"] ,"feedback_tf":["" ,""]}
, {"question": "■現在のレコードを保存またはマージできるように、Visualforceページを作成する。どのアプローチが必要ですか？" ,"choice":["カスタムコントローラー" ,"カスタムコントローラー拡張" ,"JavaScript" ,"標準コントローラーメソッド"] ,"answer":["カスタムコントローラー"] ,"feedback_tf":["" ,""]}
, {"question": "■マルチテナンシーのためにApexプログラミングのどの側面が制限されていますか" ,"choice":["アクティブなApexクラスの数" ,"Apexクラスのメソッドの数" ,"ループで処理されたレコードの数" ,"データベースクエリから返されたレコードの数"] ,"answer":["データベースクエリから返されたレコードの数"] ,"feedback_tf":["" ,""]}
, {"question": "■カスタムSVGをLightning Webコンポーネントに含めることができる3つのステップはどれ （3つ選ぶ）" ,"choice":["SVGを静的リソースとしてアップロード" ,"JavaScriptでそのゲッター？" ,"HTMLテンプレートでゲッターを参照" ,"HTMLテンプレートでインポートを参照" ,"コンテンツ。。。"] ,"answer":["SVGを静的リソースとしてアップロード" ,"JavaScriptでそのゲッター？" ,"HTMLテンプレートでゲッターを参照"] ,"feedback_tf":["" ,""]}
, {"question": "■Apexコードを使用せずに送信メッセージを送信するには、どのプロセス自動化を使用する（3つ選ぶ）" ,"choice":["ワークフロールール" ,"プロセスビルダー" ,"承認プロセス" ,"フロービルダー"] ,"answer":["ワークフロールール" ,"プロセスビルダー" ,"承認プロセス"] ,"feedback_tf":["" ,""]}
, {"question": "■アウトバンドメッセージ送信するにはどのプロセス自動化を使用する" ,"choice":["ワークフロールール" ,"プロセスビルダー" ,"承認プロセス" ,"フロービルダー"] ,"answer":["ワークフロールール"] ,"feedback_tf":["" ,""]}
, {"question": "■開発者はトラブルシューティングを行って、パフォーマンスの問題の原因を特定する必要があります、どのツールを使用すべき？" ,"choice":["AppExchange" ,"Salesforce CLI" ,"Visual Studio Core IDE" ,"開発者コンソール"] ,"answer":["開発者コンソール"] ,"feedback_tf":["" ,""]}
, {"question": "■開発者が、単体テストで失敗するが、テストコードをコピーして開発者コンソールから匿名実行すると成功した。なぜ" ,"choice":["テストメソッドのコードに構文エラー" ,"テスト方法は、サンドボックス内の既存のデータに依存しています。"] ,"answer":["テスト方法は、サンドボックス内の既存のデータに依存しています。"] ,"feedback_tf":["" ,""]}
]}
