var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"Managed Packages can be created in which type of org?", "choice":["Developer Sandbox","Unlimited Edition","Developer Edition","Partial Copy Sandbox"], "answer":["Developer Edition"] , "feedback_tf":["", ""]}
,{ "question":"Which data type or collection of data types can SOQL statements populate or evaluate to?(Choose 3)", "choice":["A single sObject","An integer","A string","A list of sObjects"], "answer":["A single sObject","An integer","A list of sObjects"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers wants Opportunities to be locked from editing when reaching theClosed/Won stage.Which two strategies should a developer use to accomplish this? (Choose two.)", "choice":["Use a Visual Workflow.","Use a validation rule.","Use the Process Automation Settings.","Use a Trigger."], "answer":["Use a validation rule.","Use a Trigger."] , "feedback_tf":["", ""]}
,{ "question":"Which two sosl searches will return records matching search criteria contained in any of thesearchable text fields on an object? choose 2 answers", "choice":["[find 'acme*' in any fields returning account,opportunity]","[find 'acme*'returning account,opportunity]","[find 'acme*'in all fields returning account,opportunity]","[find 'acme*' in text fields returning account,opportunity]"], "answer":["[find 'acme*'in all fields returning account,opportunity]"] , "feedback_tf":["", ""]}
,{ "question":"How many accounts will be inserted by the following block ofcode? for(Integer i = 0 ; i ＜ 500;i++) { Account a = new Account(Name='New Account ' + i); insert a; }", "choice":["150","0","500","100"], "answer":["0"] , "feedback_tf":["", ""]}
,{ "question":"Which three process automations can immediately send an email notification to the ownerof an Opportunity when its Amount is changed to be greater than $10,000? Choose 3 answers", "choice":["Workflow Rule (Missed)","Flow Builder","Approval Process (Missed)","Process Builder (Missed)"], "answer":["Workflow Rule (Missed)","Approval Process (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"Which two queries can a developer use in a visualforce controller to protect against SOQLinjection Vulnerabilities? Choose 2 answers", "choice":["String qryName = '%' + String.enforceSecurityChecks(name)+ '%'; String qryString = 'SELECT IdFROM Contact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryName = '%' + name '%'; String qryString = 'SELECT Id FROM Contact WHERE Name LIKE:qryNAme'; List queryResults = Database.query(qryString);","String qryName = '%' + String.escpaeSingleQuotes(name)+ '%'; String qryString = 'SELECT Id FROMContact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryString = 'SELECT Id FROM Contact WHERE Name LIKE :qryNAme'; List queryResults =Database.query(qryString);"], "answer":["String qryName = '%' + String.enforceSecurityChecks(name)+ '%'; String qryString = 'SELECT IdFROM Contact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryString = 'SELECT Id FROM Contact WHERE Name LIKE :qryNAme'; List queryResults =Database.query(qryString);"] , "feedback_tf":["", ""]}
,{ "question":"Where can the custom roll-up summary fields be created using Standard Objectrelationships (Choose 3)", "choice":["On Opportunity using Opportunity Product records.","On Account using Case records.","On Quote using Order records.","On Campaign using Campaign Member records.","On Account using Opportunity records."], "answer":["On Opportunity using Opportunity Product records.","On Campaign using Campaign Member records.","On Account using Opportunity records."] , "feedback_tf":["", ""]}
,{ "question":"When can a developer use a custom Visualforce page in a Force.com application? (Choose 2)", "choice":["To generate a PDF document with application data","To create components for dashboards and layouts","To deploy components between two organizations","To modify the page layout settings for a custom object"], "answer":["To generate a PDF document with application data","To create components for dashboards and layouts"] , "feedback_tf":["", ""]}
,{ "question":"What are two considerations for deciding to use a roll-up summary field? Choose 2 answer'spartner.", "choice":["Roll-up summary can be performed on formula fields, but if their formula contains an #Errorresult, it may affect the summary value.","Roll-up summary fields do not cause validation rules on the parent object unless that object isedited separately.","Roll-up cannot be performed on formula fields.","Roll-up cannot be performed on formula fields that use cross-object references or on-the-flycalculations such as NOW()."], "answer":["Roll-up summary can be performed on formula fields, but if their formula contains an #Errorresult, it may affect the summary value.","Roll-up cannot be performed on formula fields that use cross-object references or on-the-flycalculations such as NOW()."] , "feedback_tf":["", ""]}
]}
