var config = {"settings": {"add_css_file":false , "add_js_file":false , "custom_lang":false , "head_write_js":"" , "head_write_css":"" , "format":"table" , "messages":{"intro":"Salesforce 認定デベロッパー 練習問題"}} ,"questions":[
{"question": "【勉強会3】8.Visualforceページで、コントローラ拡張を使用する適切な例はどれ？（３つ選択）" ,"choice":["標準コントローラの編集アクションを上書きする必要がある時" ,"新しいアクションを追加する必要がある時" ,"標準コントローラの機能を置き換える必要がある時" ,"Visualforceページをユーザモードで動作させる必要がある時"] ,"answer":["標準コントローラの編集アクションを上書きする必要がある時" ,"新しいアクションを追加する必要がある時" ,"Visualforceページをユーザモードで動作させる必要がある時"] ,"feedback_tf":["標準コントローラを拡張するのが、コントローラ拡張<br>標準コントローラ部分 … ユーザモートで動作→オブジェクト権限や項目レベルセキュリティは考慮される<br>コントローラ拡張した部分 … システムモードで動作　→オブジェクト権限や項目レベルセキュリティは無視される" ,"標準コントローラを拡張するのが、コントローラ拡張<br>標準コントローラ部分 … ユーザモートで動作→オブジェクト権限や項目レベルセキュリティは考慮される<br>コントローラ拡張した部分 … システムモードで動作　→オブジェクト権限や項目レベルセキュリティは無視される"]}
, {"question": "【勉強会3】9.カスタムコントローラでの「transient」キーワード使用について誤った記述はどれ？" ,"choice":["「transient」キーワードは、VisualforceページのViewStateとして送信されず、保存しない一時変数を宣言する時に使う" ,"「transient」として変数宣言すると、ViewStateのサイズは増える" ,"「transient」キーワードはserializableなクラスでのみ使用できる" ,"「transient」キーワードは、Visualforceページで、ページ要求の間でのみ必要な項目に使用する"] ,"answer":["「transient」として変数宣言すると、ViewStateのサイズは増える"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】11.futureメソッドについて正しい記述はどれ？（２つ選択）" ,"choice":["@futureアノテーション付きメソッドは、非同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドは、同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドから、別の@futureアノテーション付きメソッドを呼び出すことが出来る" ,"@futureアノテーション付きメソッドの戻り値は「void」しか選べない"] ,"answer":["@futureアノテーション付きメソッドは、非同期実行されるメソッドであることを示す" ,"@futureアノテーション付きメソッドの戻り値は「void」しか選べない"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】12.Visualforceページで表示する項目について、ユーザが読み取りアクセス可能かどうやってチェックする？（１つ選択）" ,"choice":["Schema.DescribeFieldResultクラスのisAccessible()メソッドを呼ぶ" ,"Schema.DescribeFieldResultクラスのisViewable()メソッドを呼ぶ" ,"Schema.SObjectResultクラスのisReadable()メソッドを呼ぶ" ,"Schema.DescribeSObjectResultクラスのisAccessible()メソッドを呼ぶ"] ,"answer":["Schema.DescribeFieldResultクラスのisAccessible()メソッドを呼ぶ"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】13.プログラムから共有設定にアクセスする事に関し、正しい記述はどれ？（３つ選択）" ,"choice":["取引先オブジェクトの共有オブジェクトは「AccountShare」である。" ,"取引先オブジェクトの共有オブジェクトは「Account__Share」である。" ,"カスタムオブジェクトの共有オブジェクトは「CustomObject__Share 」である。" ,"主従関係の従側オブジェクトには、共有オブジェクトがない。"] ,"answer":["取引先オブジェクトの共有オブジェクトは「AccountShare」である。" ,"カスタムオブジェクトの共有オブジェクトは「CustomObject__Share 」である。" ,"主従関係の従側オブジェクトには、共有オブジェクトがない。"] ,"feedback_tf":["" ,""]}
, {"question": "【ポイントスタディ】ガバナ制限値で正しいものを全て選べ" ,"choice":["SOQLクエリの合計数：100" ,"SOQLクエリの合計数：1000" ,"SOQLクエリで取得される取得されるレコードの合計数：50,000" ,"SOQLクエリで取得される取得されるレコードの合計数：5,000" ,"SOSLクエリの合計数：20" ,"SOSLクエリの合計数：100" ,"DMLステートメントの合計数：150" ,"DMLステートメントの合計数：100" ,"DMLステートメントで処理されるレコードの合計数：10,000" ,"DMLステートメントで処理されるレコードの合計数：1,000"] ,"answer":["SOQLクエリの合計数：100" ,"SOQLクエリで取得される取得されるレコードの合計数：50,000" ,"SOSLクエリの合計数：20" ,"DMLステートメントの合計数：150" ,"DMLステートメントで処理されるレコードの合計数：10,000"] ,"feedback_tf":["" ,""]}
, {"question": "【ポイントスタディ】DMLステートメント数としてカウントされるメソッド2つ" ,"choice":["Database.emptyRecycleBin" ,"Database.setSavePoint" ,"Database.getDMLStatements" ,"Database.getDMLRows"] ,"answer":["Database.emptyRecycleBin" ,"Database.setSavePoint"] ,"feedback_tf":["" ,""]}
, {"question": "開発者がカスタムオブジェクト「プロジェクト」を作成しました。「取引先」画面で、関連する「プロジェクト」を集計表示する必要があります。また 「取引先」の削除時には関連するすべての「プロジェクト」を削除する必要があります。 開発者はどうするのが適切でしょうか？（1つ選択）" ,"choice":["取引先に参照関係項目を作成します。" ,"取引先に主従関係項目を作成します。" ,"プロジェクトに参照関係項目を作成します。" ,"プロジェクトに主従関係項目を作成します"] ,"answer":["プロジェクトに主従関係項目を作成します"] ,"feedback_tf":["" ,""]}
, {"question": "あなたの会社は、作業指示に割り当てられた車両を追跡する必要があります。車両は作業命令なしで存在し、レコード所有者を持つことができます。作業指示と車両の間にはどのような関係を作りますか？（1つ選択）" ,"choice":["主従関係" ,"参照関係" ,"選択リスト" ,"階層関係"] ,"answer":["参照関係"] ,"feedback_tf":["" ,""]}
, {"question": "医療従事者がどこの病院に関連しているかを追跡する必要があります。 病院は取引先オブジェクトに登録します。 医療従事者はカスタムオブジェクトです。１人の医療従事者は、複数の病院に関連させることができます。 １つの病院に複数の医療従事者に関連させることができます。この関係はどのように表現しますか？（1つ選択）" ,"choice":["医療従事者オブジェクトに主従関係項目を作成する。" ,"医療従事者オブジェクトと、取引先オブジェクト両方に主従関係項目を作成する。" ,"連結用カスタムオブジェクトを追加し、医療従事者・取引先両オブジェクトに対する　主従関係項目を作成する。" ,"医療従事者オブジェクトと、取引先オブジェクト両方に参照関係項目を作成する。"] ,"answer":["連結用カスタムオブジェクトを追加し、医療従事者・取引先両オブジェクトに対する　主従関係項目を作成する。"] ,"feedback_tf":["" ,""]}
, {"question": "開発環境にデータをインポートする際、DataLoaderとデータインポートウィザードのどちらを使用するか決定する時に何を考慮しますか？ （3つ選択）" ,"choice":["ロードするレコードの数" ,"データを複数回読み込む必要があるか" ,"オブジェクトがデータインポートウィザードでサポートされているか" ,"データのインポート時にトリガを実行する必要があるか"] ,"answer":["ロードするレコードの数" ,"データを複数回読み込む必要があるか" ,"オブジェクトがデータインポートウィザードでサポートされているか"] ,"feedback_tf":["" ,""]}
, {"question": "開発者は開発環境に100件のカスタムオブジェクトレコードを1回インポートする。 データはCSVファイルで、各レコードには5つのフィールドが含まれています。 どのツールを使用してデータをロードすることをお勧めしますか？（1つ選択）" ,"choice":["カスタムオブジェクトインポートウィザード" ,"データインポートウィザード" ,"DataLoader" ,"データAPIツール"] ,"answer":["データインポートウィザード"] ,"feedback_tf":["" ,""]}
, {"question": "開発者は、インポートファイルを使用して既存の取引先を更新する必要があります。 正しいレコードが更新されるようにレコードをどのように照合できますか？（2つ選択）" ,"choice":["インポートファイルのある列と、レコードIDを一致させます。" ,"インポートファイルのある列と、取引先名を一致させます" ,"インポートファイル内のデータの順序をSalesforceのレコードの順序と一致させる" ,"インポートファイルのある列と、取引先オブジェクトに定義した外部ID項目と一致させる"] ,"answer":["インポートファイルのある列と、レコードIDを一致させます。" ,"インポートファイルのある列と、取引先オブジェクトに定義した外部ID項目と一致させる"] ,"feedback_tf":["" ,""]}
, {"question": "次の中で、オブジェクトや関係を表示および動的に変更できる環境はどれですか？（1つ選択）" ,"choice":["スキーマビルダー" ,"プロセスビルダー" ,"プロセスビジュアライザ" ,"承認ビジュアライザ" ,"フロー"] ,"answer":["スキーマビルダー"] ,"feedback_tf":["" ,""]}
, {"question": "ユニバーサルコンテナ社はスキーマビルダーを利用しましたがオブジェクトや関係が多すぎて読み込み時間が長くなり、作業が難しいと判断しました。 この問題を解決するためにどのような機能を提案しますか？ （3つ選択）" ,"choice":["「リレーションを非表示」オプションを選択すると、パフォーマンスが向上します。" ,"マップを使用して関心のあるオブジェクトにナビゲートできます。" ,"フィルタを使用して、関心のあるオブジェクトのみを表示することができます。" ,"項目を隠すことができ、オブジェクトのみ表示することができます"] ,"answer":["「リレーションを非表示」オプションを選択すると、パフォーマンスが向上します。" ,"マップを使用して関心のあるオブジェクトにナビゲートできます。" ,"フィルタを使用して、関心のあるオブジェクトのみを表示することができます。"] ,"feedback_tf":["" ,""]}
, {"question": "スキーマビルダーでできないものはどれですか？（1つ選択）" ,"choice":["カスタムオブジェクトの作成" ,"カスタムオブジェクトの削除" ,"主従関係・参照関係を作成する" ,"スキーマ定義のエクスポート"] ,"answer":["カスタムオブジェクトの作成" ,"カスタムオブジェクトの削除" ,"主従関係・参照関係を作成する"] ,"feedback_tf":["" ,""]}
, {"question": "以下ソースの変数「isCorrect」の型は何？<pre><br>If(isCorrect){<br>    System.debug(“The value of x is True”);<br>} else if (!isCorrect) {<br>    System.debug(“The value of x is False”);<br>} else {<br>    System.debug(“The value of x is Null”);<br>}<br></pre>" ,"choice":["Blob" ,"String" ,"Boolean" ,"Enum"] ,"answer":["Boolean"] ,"feedback_tf":["" ,""]}
, {"question": "以下の内、SOQLで取得したレコードを格納できるデータ型はどれ？" ,"choice":["List" ,"Group" ,"Enum" ,"Container"] ,"answer":["List"] ,"feedback_tf":["" ,""]}
, {"question": "通貨項目が自動的に割り当てられるデータ型はどれ？" ,"choice":["Currency" ,"Number" ,"Decimal" ,"Long"] ,"answer":["Decimal"] ,"feedback_tf":["" ,""]}
, {"question": "値を設定する次のステートメント文で正しいのはどれ？" ,"choice":["String a = new String('sampleString');" ,"Map<Id, Account> = [SELECT Id, Name FROM Account];" ,"Account acc = new Account();" ,"List<Contact> conList = new [SELECT Id FROM Contact];"] ,"answer":["Account acc = new Account();"] ,"feedback_tf":["" ,""]}
, {"question": "以下のApex変数宣言で正しくないのはどれ？" ,"choice":["Map<ID, String> sampleMap;" ,"Boolean y;" ,"String a,b,c;" ,"Currency abc;"] ,"answer":["Currency abc;"] ,"feedback_tf":["" ,""]}
, {"question": "以下の内、より良い定数宣言はどれ？" ,"choice":["static final Integer privCons = 200;" ,"private String privCons = ‘Private’;" ,"public static String privCons = ‘Private’;" ,"global static Integer privCons = 250;"] ,"answer":["static final Integer privCons = 200;"] ,"feedback_tf":["" ,""]}
, {"question": "以下List初期化宣言の内、正しくないのはどれ？" ,"choice":["List<Account> accList = new List<Account>();" ,"Account[] accList = new Account[]{};" ,"List<Account> new = ‘accList’;" ,"List<Account> accList = new Account[]{};"] ,"answer":["List<Account> new = ‘accList’;"] ,"feedback_tf":["" ,""]}
, {"question": "「testRawScore」が75の時、以下のソースを実行すると何がデバッグ出力される？<pre><br>if (testRawScore >= 90) {<br>    gradeEqual = ‘A’;<br>}<br>if (testRawScore >= 80) {<br>    gradeEqual = ‘B’;<br>}<br>if (testRawScore >= 70) {<br>    gradeEqual = ‘C’;<br>}<br>if (testRawScore >= 60) {<br>    gradeEqual = ‘D’;<br>}<br>System.debug(gradeEqual);<br></pre>" ,"choice":["A" ,"B" ,"C" ,"D"] ,"answer":["D"] ,"feedback_tf":["" ,""]}
, {"question": "以下のソースを実行すると何がデバッグ出力される？<pre><br>Integer z = 5;<br>do {<br>    z = z + 1;<br>} while(z < = 15);<br><br>System.debug(z);<br>]<br></pre>" ,"choice":["13" ,"14" ,"15" ,"16"] ,"answer":["16"] ,"feedback_tf":["" ,""]}
, {"question": "下記コードに関する記述で正しいのはどれ？（２つ選択）<pre><br>public with sharing class containerClass {<br>    //Insert code here<br><br>    public class innerClass {<br>        //Insert code here<br>    }<br>}<br></pre>" ,"choice":["innerClassはcontainerClassの共有設定を継承しない。" ,"[with/without sharing]キーワードは、外部クラスでのみ定義する必要がある。" ,"内部クラスの共有設定デフォルトは、[without sharing]である。" ,"innerClassはcontainerClassの共有設定を継承する。"] ,"answer":["innerClassはcontainerClassの共有設定を継承しない。" ,"内部クラスの共有設定デフォルトは、[without sharing]である。"] ,"feedback_tf":["" ,""]}
, {"question": "以下のソースを実行すると何が起こる？<pre><br>try {<br> String sampleStr;<br> if (sampleStr.contains(‘abcd’)) {<br>  system.debug(‘Hello World’);<br> }<br>}catch(DmlException e) {<br> System.debug(‘DmlException: ‘ + e.getMessage());   ①<br>}catch(SObjectException e) {<br> System.debug(‘SObjectException: ‘ + e.getMessage());   ②<br>}catch(ListException e) {<br> System.debug(‘ListException: ‘ + e.getMessage());   ③<br>}catch(Exception e) {<br> System.debug(‘Exception: ‘ + e.getMessage());  ④<br>}<br></pre>" ,"choice":["④だけ実行" ,"①~④は実行されず、例外発生" ,"①～④全部実行される" ,"①～④は実行されず、例外発生せず"] ,"answer":["④だけ実行"] ,"feedback_tf":["" ,""]}
, {"question": "以下の内、誤ったカスタム例外の投げ方はどれ？" ,"choice":["throw new customExceptionName();" ,"throw new customExceptionName().addError(‘Error Message Here’)" ,"throw new customExceptionName(‘Error Message Here’);" ,"throw new customExceptionName(e);"] ,"answer":["throw new customExceptionName().addError(‘Error Message Here’)"] ,"feedback_tf":["" ,""]}
, {"question": "以下のトリガーはどのイベントで起動すべきですか？ Trigger createCallingCard on Contact (EVENT) { List<CallingCard__c> cardList = new List<CallingCard__c>(); for (Contact con : Trigger.new) {  CallingCard__c newCard = new CallingCard__c();  newCard.Name = con.Name;  newCard.Phone = con.Phone;  newCard.Address = con.Address;  newCard.relatedContact__c = con.Id;  cardList.add(newCard); } insert cardList;}" ,"choice":["After Update" ,"Before Delete" ,"After Insert" ,"Before Insert"] ,"answer":["After Insert"] ,"feedback_tf":["" ,""]}
, {"question": "以下の要件があります。開発者はどのイベントのトリガーを作成すべきですか？項目「isPrimaryContact」＝trueの取引先責任者レコードが削除される度、関連する取引先のhasPrimaryContactフィールドをfalseに更新する" ,"choice":["Before Update" ,"Before Delete" ,"After Update" ,"After Delete"] ,"answer":["After Delete"] ,"feedback_tf":["" ,""]}
]}
