var config = {"settings": {"add_css_file":false , "add_js_file":false , "custom_lang":false , "head_write_js":"" , "head_write_css":"" , "format":"table" , "messages":{"intro":"Salesforce 認定デベロッパー 練習問題"}} ,"questions":[
{"question": "【過去問(S)】16.Lightningコンポーネントバンドルに含まれるものは？2つ" ,"choice":["Javascript" ,"画像" ,"Apexクラス" ,"ドキュメント"] ,"answer":["Javascript" ,"ドキュメント"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(S)】17.SOSLの戻り値は？" ,"choice":["SObjectのリスト" ,"SObjectのリストのリスト" ,"SObject型とSObjectのMap"] ,"answer":["SObjectのリストのリスト"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(N)】5.取引責任者を持たない取引先名NoContactsのデータで実行した場合の結果は？<br>List a = new List([select Id,Name ,(select id,name from contacts) from account where Name = 'NoContacts']);" ,"choice":["a[0].contacts は、null" ,"a[0].contacts は、空リスト" ,"a[0]は、null" ,"apexエラーになる"] ,"answer":["a[0]は、null"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(N)】6.＜ltng:require＞の機能は？（3つ選択）" ,"choice":["1回のみ読み込み" ,"並列読み込み" ,"外部javascriptの読み込み" ,"ドキュメントの読み込み"] ,"answer":["1回のみ読み込み" ,"並列読み込み" ,"外部javascriptの読み込み"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(N)】8.セールス、セールスマネージャーで両方が使うvisualforce画面がある。その画面でxxx__cという項目は、プロファイルの項目レベルセキュリティでセールスマネージャーだけが、参照できるように設定している。将来のメンテナンス性を考慮して開発者が取る方法はどれ？" ,"choice":["両方のプロファイルで使うvisualforce画面を1つ作成" ,"with sharingキーワードを使用したカスタムコントローラを作る" ,"それぞれのプロファイルで使うvisualforce画面を2つ作成" ,"新しいセールスマネージャーには、権限セットを割り当てる。"] ,"answer":["両方のプロファイルで使うvisualforce画面を1つ作成"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】1.キャンペーンメンバー〜で取引先、取引先責任者、商談を作成した場合、キャンペーンメンバーが新たに参照するオブジェクトは？（1つ選択）" ,"choice":["取引先" ,"取引先責任者" ,"商品" ,"商談"] ,"answer":["取引先責任者"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】2.パラメータの戻り値の型ページURLに含まれるパラメータをgetParametersで取得した時の型は？" ,"choice":["Map＜String, String＞" ,"String[]" ,"List" ,"String"] ,"answer":["Map＜String, String＞"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】3.メール一括送信（夜間バッチで数万件商談作成後、取引先とリードに合ってるかメールを送る）、パフォーマンスを気にしている（2つ選ぶ）" ,"choice":["AppExchange" ,"Apex" ,"プロセスビルダー" ,"ワークフロー"] ,"answer":["AppExchange" ,"Apex"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】4.本番環境のApexクラスの削除方法" ,"choice":["Workbench" ,"開発者コンソール" ,"Force.com IDE"] ,"answer":["Workbench"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】8.Sample.cmp を作った、画面でカーソルを当てた時にcmpを呼び出すのはどのバンドルか" ,"choice":["sampleHelper.js" ,"sample.helper" ,"sampleRenderer.js" ,"sample.renderer"] ,"answer":["sampleHelper.js"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】9.Visualforceで使用するcssの方法(3つ選択)" ,"choice":["apex:stylesheets" ,"apex:stylesheet" ,"静的リソース" ,"インライン" ,"apex:style"] ,"answer":["apex:stylesheet" ,"静的リソース" ,"インライン"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】10.開発者コンソールで出力するログレベルはどこから変更するか1つ選択" ,"choice":["[設定]メニューから" ,"Editメニューから" ,"Debugメニューから" ,"Logsメニューから"] ,"answer":["Debugメニューから"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】11.ヒープエラーになった、対応2つ選択" ,"choice":["変数にtransientつける" ,"使わないコレクションをnullまたは空にする" ,"SOQL for Loopにする"] ,"answer":["使わないコレクションをnullまたは空にする" ,"SOQL for Loopにする"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】12.テスト内でガバナ制限に引っかかってるから確認する方法1つ選ぶ" ,"choice":["Test.getDmlStatementsを使う" ,"Limit、startTest、stopTest使う" ,"Limit、startTest、endTest使う"] ,"answer":["Limit、startTest、stopTest使う"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】14.映画と俳優と契約の3オブジェクト、契約が映画と俳優を1つずつ持つ時の関連付けはどれにすればよいか" ,"choice":["2つとも主従" ,"2つとも参照" ,"片方が参照、片方が主従（がそれぞれ）"] ,"answer":["2つとも主従"] ,"feedback_tf":["連結オブジェクトの話" ,"連結オブジェクトの話"]}
, {"question": "【過去問(U)】16.SOQLのインジェクションを防ぐ方法2つ選択" ,"choice":["実際のコードの中から選択する" ,"like検索→文字結合" ,"like検索　文字結合（String.escapeSingleQuotes）" ,"バインド変数" ,"バインド変数（String.escapeSingleQuotes実施した変数）"] ,"answer":["like検索　文字結合（String.escapeSingleQuotes）" ,"バインド変数"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】20.with sharing で作ったメソッドを、営業所の部長とその配下にのみ、取引先が見えるようにしたい、やるべきこと" ,"choice":["プロファイル1つ、権限セット1つ、ロール1つ" ,"プロファイル2つ、権限セット1つ、ロール1つ" ,"プロファイル1つ、権限セット2つ、ロール1つ" ,"プロファイル1つ、権限セット1つ、ロール2つ"] ,"answer":["プロファイル1つ、権限セット1つ、ロール2つ"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】21.汎用的なオブジェクトを受け取るメソッドを作った、内部でどのオブジェクトか判定するには？" ,"choice":["getSObjectTypeでオブジェクトのトークンを取得して判定" ,"getSObjectNameでオブジェクト名を取得して判定"] ,"answer":["getSObjectTypeでオブジェクトのトークンを取得して判定"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】22.単体テストで失敗するが、テストコードをコピーして開発者コンソールから匿名実行すると成功した。失敗する原因は何か？" ,"choice":["テストコードにtry/catchが入っている" ,"テストコードに@futureがある" ,"テストコードに構文エラーがある" ,"テストコードが既存のデータに依存している"] ,"answer":["テストコードが既存のデータに依存している"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】25.商談のステータスが更新されたら、取引先を更新した上で商談商品の内容を納品商品？にレコード追加したい（みたいな内容）<br>何を使えば実現できるか？" ,"choice":["ワークフロー" ,"プロセスビルダー" ,"ワークフローとプロセスビルダー" ,"プロセスビルダーからフロー"] ,"answer":["プロセスビルダー"] ,"feedback_tf":["" ,""]}
, {"question": "【過去問(U)】29.簡単なテキストを返すLightningコンポーネントを作成した。これを他の複数のApexから使えるようにするにはどうしたら良いか？" ,"choice":["各クラスにgetMessageText()を実装する" ,"インターフェースを継承してgetMessageText()を実装する" ,"getMessageText()を実装したクラスを継承する"] ,"answer":["getMessageText()を実装したクラスを継承する"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会1】8.ユニバーサルコンテナ社はスキーマビルダーを利用しましたがオブジェクトや関係が多すぎて読み込み時間が長くなり、作業が難しいと判断しました。 この問題を解決するためにどのような機能を提案しますか？ 3 つ選択）" ,"choice":["「リレーションを非表示」オプションを選択すると、パフォーマンスが向上します。" ,"マップを使用して関心のあるオブジェクトにナビゲートできます。" ,"フィルタを使用して、関心のあるオブジェクトのみを表示することができます。" ,"項目を隠すことができ、オブジェクトのみ表示することができます"] ,"answer":["「リレーションを非表示」オプションを選択すると、パフォーマンスが向上します。" ,"マップを使用して関心のあるオブジェクトにナビゲートできます。" ,"フィルタを使用して、関心のあるオブジェクトのみを表示することができます。"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会1】9.スキーマビルダーでできないものはどれですか？（1つ選択）" ,"choice":["カスタムオブジェクトの作成" ,"カスタムオブジェクトの削除" ,"主従関係・参照関係を作成する" ,"スキーマ定義のエクスポート"] ,"answer":["スキーマ定義のエクスポート"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会2】16.トリガのカスケード実行（連鎖実行）について正しい記述はどれか（1つ選択）" ,"choice":["トリガのカスケード実行により例外が発生する" ,"カスケード実行トリガも、同じ実行コンテキストで動作しガバナ制限を共有する" ,"各トリガーは新しい実行コンテキストを開始します" ,"カスケード実行できるトリガーは 5 つまで との制限がある"] ,"answer":["カスケード実行トリガも、同じ実行コンテキストで動作しガバナ制限を共有する"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】2.Apexトリガを書くとき、何を考慮しておく必要がある？（２つ選択）" ,"choice":["オブジェクト毎に、Apexトリガは一つにする必要がある" ,"Apexトリガにはロジックを書かず、Handlerクラスに移譲する" ,"Apexトリガは他のトリガを起動すべきでない" ,"ApexトリガはDML実行時に@futureアノテーションを付けるべき"] ,"answer":["オブジェクト毎に、Apexトリガは一つにする必要がある" ,"Apexトリガにはロジックを書かず、Handlerクラスに移譲する"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】3.次のコードのうち、ループ文に含めてはいけないのは？（２つ選択）" ,"choice":["insert accountList;" ,"System.debug(‘The following account has been updated’ + ‘acc.Id ‘);" ,"Opportunity getOpp = [SELECT Id, AccountId FROM Opportunity WHERE AccountId =: acc.Id]; " ,"if(acc.NumberOfEmployees ＞ 5000)"] ,"answer":["insert accountList;" ,"Opportunity getOpp = [SELECT Id, AccountId FROM Opportunity WHERE AccountId =: acc.Id]; "] ,"feedback_tf":["SOQL実行(100回まで)も、DML実行(150回まで)も、ループ内でやっちゃだめ！" ,"SOQL実行(100回まで)も、DML実行(150回まで)も、ループ内でやっちゃだめ！"]}
, {"question": "【勉強会3】4.以下の標準オブジェクトの内、DML操作のサポート外なのはどれ？（２つ選択）" ,"choice":["プロファイル" ,"ユーザー" ,"ケース" ,"レコードタイプ"] ,"answer":["プロファイル" ,"レコードタイプ"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】5.検索結果に含める情報を指定するにはSOSL文に何句を追加する？（１つ選択）" ,"choice":["LIMIT n" ,"RETURNING" ,"OFFSET n" ,"ORDER BY"] ,"answer":["RETURNING"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】6.下記SOSL文の検索結果で、取引先60件が抽出される想定だったが、実際は取引先20件。SOSLのLIMIT指定について正しい記述は？（１つ選択）<br>　FIND {test} RETURNING Account(id), Contact, Opportunity LIMIT 60" ,"choice":["SOSLクエリではLIMIT指定ができない" ,"検索結果が戻ってきたオブジェクトで均等に分割された" ,"LIMITはオブジェクト毎に個別指定しなければならない" ,"上記SOSLは構文が正しくない"] ,"answer":["検索結果が戻ってきたオブジェクトで均等に分割された"] ,"feedback_tf":["" ,""]}
, {"question": "【勉強会3】7.Visualforceページで、カスタムコントローラを使用する適切な例はどれ？（２つ選択）" ,"choice":["標準コントローラの編集アクションを上書きする必要がある時" ,"Visualforceページをシステムモードで実行する必要がある時" ,"Visualforceページで、標準コントローラの機能を置き換える必要がある時" ,"Visualforceページで、標準コントローラの保存アクションを上書きする必要がある時"] ,"answer":["Visualforceページをシステムモードで実行する必要がある時" ,"Visualforceページで、標準コントローラの機能を置き換える必要がある時"] ,"feedback_tf":["" ,""]}
]}
