var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[

{ "question":"A Visualforce page has a standard controller for an object that has a lookup relationship to aparent object.How can a developer display data from the parent record on the page?", "choice":["By adding a second standard controller to the page for the parent record.","By using a roll-up formula field on the child record to include data from the parent record.","By using SOQL on the Visualforce page to query for data from the parent record.","By using merge field syntax to retrieve data from the parent record."], "answer":["By using merge field syntax to retrieve data from the parent record."] , "feedback_tf":["", ""]}
,{ "question":"How can a developer retrieve all Opportunity record type labels to populate a listcollection?Choose 2 answers", "choice":["Obtain describe object results for the Opportunity objct.","Write a for loop that extracts values from the Opportunity.RecordType.Name field.","Use the global variable $RecordType and extract a list from the map.","Write a SOQL for loop that iterates on the RecordType object."], "answer":["Obtain describe object results for the Opportunity objct.","Write a SOQL for loop that iterates on the RecordType object."] , "feedback_tf":["", ""]}
,{ "question":"What is a capability of the ＜ltng:require＞ tag that is used for loading external Javascriptlibraries in Lightning Component? (Choose three.)", "choice":["Loading files from Documents.","One-time loading for duplicate scripts.","Specifying loading order.","Loading scripts in parallel."], "answer":["One-time loading for duplicate scripts.","Specifying loading order.","Loading scripts in parallel."] , "feedback_tf":["", ""]}
,{ "question":"Which three code lines are required to create a Lightning component on a Visualforce page?Choose 3 answers", "choice":["$Lightning.createComponent","＜apex:slds/＞","$Lightning.useComponent","$Lightning.use (Missed)","＜apex:includeLightning/＞"], "answer":["$Lightning.createComponent","$Lightning.use (Missed)","＜apex:includeLightning/＞"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers wants a list button to display a Visualforce page that allows users to editmultiple records. which Visualforce feature supports this requirement?", "choice":["＜apex:listButton＞ tag","Custom controller","RecordSetVar page attribute","Controller extension"], "answer":["RecordSetVar page attribute"] , "feedback_tf":["", ""]}
,{ "question":"A company has a custom object named Region. Each account in salesforce can only be relatedto one region at a time, but this relationship is optional. Which type of relantionship should adeveloper use to relate an account to a region?", "choice":["Parent-child","Master-detail","Hierarchical","Lookup"], "answer":["Master-detail"] , "feedback_tf":["", ""]}
,{ "question":"A developer in a Salesforce org with 100 Accounts executes the following code using theDeveloper console:Account myAccount = new Account(Name = 'MyAccount');Insert myAccount;For (Integer x = 0; x ＜250; x++){Account newAccount = new Account (Name='MyAccount' + x);try {Insert newAccount;}catch(Exception ex) {System.debug (ex) ;}}insert new Account (Name='myAccount'); How many accountsare in the org after this code is run?", "choice":["101","100","102","252"], "answer":["100"] , "feedback_tf":["", ""]}
,{ "question":"Which is a valid apex assignment?", "choice":["Integer x=5 * 1,0","Integer = 5,0","Double x = 5","Float x = 5.0"], "answer":["Double x = 5"] , "feedback_tf":["", ""]}
,{ "question":"A developer has a single custom controller class that works with a Visualforce Wizard tosupport creating and editing multiple sObjects. The wizard accepts data from user inputs acrossmultiple Visualforce pages and from a parameter on the initial URLWhich statement is unnecessaryinside the unit test for the custom controller?", "choice":["Public ExtendedController (ApexPages.StandardController cntrl) { }","ApexPages.currentPage().getParameters().put('input', 'TestValue')","Test.setCurrentPage(pageRef),","String nextPage = controller.save().getUrl();"], "answer":["Public ExtendedController (ApexPages.StandardController cntrl) { }","String nextPage = controller.save().getUrl();"] , "feedback_tf":["", ""]}
,{ "question":"Which three tools can deploy metadata to production? (Choose three.)", "choice":["Change Set from Developer Org","Force.com IDE","Data Loader","Change Set from Sandbox","Metadata API"], "answer":["Change Set from Developer Org","Change Set from Sandbox","Metadata API"] , "feedback_tf":["", ""]}
,{ "question":"A developer observes that an Apex test method fails in the Sandbox. To identify the issue, thedeveloper copies the code inside the test method and executes it via the Execute Anonymous tool inthe Developer Console. The code then executes with no exceptions or errors. Why did the testmethod fail in the sandbox and pass in the Developer Console?", "choice":["The test method has a syntax error in the code.","The test method relies on existing data in the sandbox.","The test method is calling an @future method.","The test method does not use System.runAs to execute as a specific user."], "answer":["The test method relies on existing data in the sandbox."] , "feedback_tf":["", ""]}
,{ "question":"Which code in a Visualforce page and/or controller might present a security vulnerability?", "choice":["＜apex:outputField value= {!ctrl.userInput}  /＞","＜apex:outputText escape= false  value=  {!$CurrentPage.parameters.userInput}  /＞","＜apex:outputText value= {!$CurrentPage.parameters.userInput}  /＞","＜apex:outputField escape= false  value= {!ctrl.userInput}  /＞"], "answer":["＜apex:outputText escape= false  value=  {!$CurrentPage.parameters.userInput}  /＞"] , "feedback_tf":["", ""]}
,{ "question":"What are two ways a developer can get the status of an enquered job for a class thatqueueable interface?Choose 2 answers", "choice":["View the apex status Page","View the apex flex Queue","View the apex Jobs page (Missed)","Query the AsyncApexJobe object (Missed)"], "answer":["View the apex Jobs page (Missed)","Query the AsyncApexJobe object (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"The Sales Management team hires a new intern. The intern is not allowed to viewOpportunities, but needs to see the Most Recent Closed Date of all child Opportunities when viewingan Account record. What would a developer do to meet this requirement?", "choice":["Create a trigger on the Account object that queries the Close Date of the most recentOpportunities.","Create a Workflow rule on the Opportunity object that updates a field on the parent Account.","Create a formula field on the Account object that performs a MAX on the Opportunity Close Datefield.","Create a roll-up summary field on the Account object that performs a MAX on the OpportunityClose Date field."], "answer":["Create a roll-up summary field on the Account object that performs a MAX on the OpportunityClose Date field."] , "feedback_tf":["", ""]}
,{ "question":"A developer is creating an enhancement to an application that will allow people to be relatedto their employer.Which data model provides the simplest solution to meet the requirements?", "choice":["Create a lookup realtionship to indicate that a person has an employer","Create a master-detail relationship to indicate that a person has an employer","Create a junction object to relate many people to many through master-detail relationship","Create a junction object to relate many people to many through lookup relationship"], "answer":["Create a master-detail relationship to indicate that a person has an employer"] , "feedback_tf":["", ""]}
,{ "question":"What is the result of the debug statements in testMethod3 when you create test data usingtestSetup in below code?", "choice":["Account0.Phone=333-8781, Account1.Phone=333-8780","Account0.Phone=888-1515, Account1.Phone=999-2525","Account0.Phone=333-8780, Account1.Phone=333-8781","Account0.Phone=888-1515, Account1.Phone=999-1515"], "answer":["Account0.Phone=333-8780, Account1.Phone=333-8781"] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of using an after insert trigger over using a before insert trigger?", "choice":["An after insert trigger allows a developer to bypass validation rules when updating fields on thenew record.","An after insert trigger allows a developer to insert other objects that reference the new record.","An after insert trigger allows a developer to make a callout to an external service.","An after insert trigger allows a developer to modify fields in the new record without a query."], "answer":["An after insert trigger allows a developer to insert other objects that reference the new record."] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of using an after insert trigger over using a before insert trigger?", "choice":["An after insert trigger allows a developer to bypass validation rules when updating fields on thenew record.","An after insert trigger allows a developer to insert other objects that reference the new record.","An after insert trigger allows a developer to make a callout to an external service.","An after insert trigger allows a developer to modify fields in the new record without a query."], "answer":["An after insert trigger allows a developer to insert other objects that reference the new record."] , "feedback_tf":["", ""]}
,{ "question":"An Apex transaction inserts 100 Account records and 2,000 Contact records beforeencountering a DML exception when attempting to insert 500 Opportunity records. The Accountrecords are inserted by calling the database.insert() method with the allOrNone argument set tofalse. The Contact and Opportunity records are inserted using the standalone insert statement. Howmany total records will be committed to the database in this transaction?", "choice":["100","2000","2100","0"], "answer":["100"] , "feedback_tf":["", ""]}
,{ "question":"Which set of roll-up types are available when creating a roll-up summary field?", "choice":["COUNT, SUM, MIN, MAX","AVERAGE, SUM, MIN, MAX","SUM, MIN, MAX","AVRAGE, COUNT, SUM, MIN, MAX"], "answer":["COUNT, SUM, MIN, MAX"] , "feedback_tf":["", ""]}
,{ "question":"A developer in a Salesforce org with 100 Accounts executes the following code using theDeveloper console:Account myAccount = new Account(Name = 'MyAccount');Insert myAccount;For(Integer x = 0; x ＜150; x++){Account newAccount = new Account (Name='MyAccount' + x);try {Insert newAccount;} catch(Exception ex) {System.debug (ex) ;}}insert new Account (Name='myAccount');How many accountsare in the org after this code is run?", "choice":["101","100","102","252"], "answer":["100"] , "feedback_tf":["", ""]}
,{ "question":"Which action can a developer perform in a before update trigger? (Choose 2)", "choice":["Display a custom error message in the application interface.","Change field values using the Trigger.new context variable.","Delete the original object using a delete DML operation.","Update the original object using an update DML operation."], "answer":["Display a custom error message in the application interface.","Change field values using the Trigger.new context variable."] , "feedback_tf":["", ""]}
,{ "question":"Which two roll-up summary field types are required to find the average of values on detailrecords in a Master-Detail relationship?", "choice":["Roll-up summary field of type COUNT","Roll-up summary field of type SUM","Roll-up summary field of type NUM","Roll-up summary field of type TOTAL"], "answer":["Roll-up summary field of type COUNT","Roll-up summary field of type SUM"] , "feedback_tf":["", ""]}
,{ "question":"What is the data type returned by the following SOSL search? {FIND 'Acme*' in name fieldsreturning account,opportunity};", "choice":["List＜List＜Account＞,List＜Opportunity＞","Map＜sObject,sObject＞","Map＜Id,sObject＞","List＜List＜sObject＞＞"], "answer":["List＜List＜sObject＞＞"] , "feedback_tf":["", ""]}
,{ "question":"A candidate may apply to multiple jobs at the company Universal Containers by submtting asingle application per job posting. Once an application is submitted for a job posting, that applicationcannot be modified to be resubmitted to a different job posting.What can the administrator do toassociate an application with each job posting in the schema for the organization?", "choice":["Create a master-detail relationship in the Job Postings custom object to the Applications customobject.","Create a master-detail relationship in the Application custom object to the Job Postings customobject.","Create a lookup relationship on both objects to a junction object called Job Posting Applications.","Create a lookup relationship in the Applications custom object to the Job Postings custom object"], "answer":["Create a master-detail relationship in the Job Postings custom object to the Applications customobject."] , "feedback_tf":["", ""]}
,{ "question":"Which declarative method helps ensure quality data? (Choose 3)", "choice":["Validation Rules","Workflow alerts","Exception Handling","Lookup Filters","Page Layouts"], "answer":["Validation Rules","Lookup Filters","Page Layouts"] , "feedback_tf":["", ""]}
,{ "question":"A developer writes a SOQL query to find child records for a specific parent. How many levelscan be returned in a single query?", "choice":["1","7","5","3"], "answer":["5"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to create an audit trail for records that are sent to the recycle bin. Whichtype of trigger is most appropriate to create?", "choice":["Before delete","After undelete","After delete","Before undelete"], "answer":["After undelete"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to update an unrelated object when a record gets saved. Which twotrigger types should the developer create?", "choice":["After insert","After update","Before update","Before insert"], "answer":["Before update","Before insert"] , "feedback_tf":["", ""]}
,{ "question":"A developer created a Visualforce page with a custom controller to show a list of accounts.The page uses the＜apex:SelecList＞ component, with a variable called  selection , to show the valid values forAccount.Type.The page uses an ＜apex:pageBlockTable＞ component to display the list of accounts, where theiteration variable is  acct . The developer wants to ensure that when a user selects a type on the＜apex : selectList＞ component, only accounts with that type are shown on the page. What should thedeveloper do to accomplish this?", "choice":["Use the onChange event to update the list of accounts in the controller when the value changes,and then re-render the pageBlockTable.","Create multiple lists in the controller that represent the relevant accounts for each account typewhen the page loads, then reference the correct one dynamically on the pageBlockTable.","Add the Rendered={!Acct.type==selection} attribute to the pageBlockTable component","Create a component for each option and use a variable with hide parameter on the element."], "answer":["Use the onChange event to update the list of accounts in the controller when the value changes,and then re-render the pageBlockTable."] , "feedback_tf":["", ""]}
,{ "question":"A company wants to create an employee rating program that allows employees to rate eachother. An employees average rating must be displayed on the employee record. Employees must beable to create rating records, but are not allowed to create employee records. Which two actionsshould a developer take to accomplish this task?", "choice":["Create a trigger on the Rating object than updates a field on the Employee object.","Create a roll-up summary field on the Employee and use AVG to calculate the average rating score.","Create a lookup relationship between the Rating and Employee object.","Create a master-detail relationship between the Rating and Employee objects."], "answer":["Create a roll-up summary field on the Employee and use AVG to calculate the average rating score."] , "feedback_tf":["", ""]}
,{ "question":"Candidates are reviewed by four separate reviewers and their comments and scores whichrange from 1 (lowest) to 5 (highest) are stored on a review record that is a detail record for acandidate what is the best way to indicate that a combined review score of 15 of better is required torecommend that the candidate come in for an interview?", "choice":["Use a validation rule on a total score field on the candidate record that prevents a recommendedfield from being true if the total score is less than 15","Use a workflow rule to calculate the sum of the review scores and send an email to the hiringmanager when the total is 15 or better","Use visual workflow to set a recommended field on the candidate whenever the cumulativereview score is 15 or better","Use a rollup summary field to calculates the sum of the review scores, and store this in a totalscore field on the candidate"], "answer":["Use a workflow rule to calculate the sum of the review scores and send an email to the hiringmanager when the total is 15 or better"] , "feedback_tf":["", ""]}
,{ "question":"A developer is asked to create a PDF quote document formatted using the company'sbranding guidelines, and automatically save it to the Opportunity record.Which two ways should a developer create this functionality? (Choose two.)", "choice":["Install an application from the AppExchange to generate documents.","Create a Visualforce page with custom styling.","Create an email template and use it in Process Builder.","Create a visual flow that implements the company's formatting."], "answer":["Install an application from the AppExchange to generate documents.","Create a Visualforce page with custom styling."] , "feedback_tf":["", ""]}
,{ "question":"Which statement is true about a hierarchical relationship as it pertains to user records?", "choice":["It uses a junction object and lookup relationships to allow many user records to be related tomany other user records","It uses a junction object and master-detail relationship to allow many user records to be related tomany other user records","It uses a master-detail relationship to allow one user record to be related to another user record","It uses a special lookup relationship to allow one user record to be related to another user record"], "answer":["It uses a special lookup relationship to allow one user record to be related to another user record"] , "feedback_tf":["", ""]}
,{ "question":"Which statement results in an Apex compiler error?", "choice":["Map＜Id,Leas＞ lmap = new Map＜Id,Lead＞([Select ID from Lead Limit 8]);","Date d1 = Date.Today(), d2 = Date.ValueOf('2018-01-01');","Integer a=5, b=6, c, d = 7;","List＜string＞ s = List＜string＞{'a','b','c');"], "answer":["List＜string＞ s = List＜string＞{'a','b','c');"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to create a Visualforce page that displays Case data. The page will beused by both support reps and support managers. The Support Rep profile does not allow visibility ofthe Customer_Satisfaction__c field, but the Support Manager profile does.How can the developer create the page to enforce Field Level Security and keep future maintenanceto a minimum?", "choice":["Create one Visualforce Page for use by both profiles.","Use a new Support Manager permission set.","Create a separate Visualforce Page for each profile.","Use a custom controller that has the with sharing keywords."], "answer":["Use a custom controller that has the with sharing keywords."] , "feedback_tf":["", ""]}
,{ "question":"A company that uses a Custom object to track candidates would like to send candidateinformation automatically to a third -party human resource system when a candidate is hired. Whatcan a developer do to accomplish this task?", "choice":["Create an escalation rule to the hiring manager.","Create an auto response rule to the candidate.","Create a Process Builder with an outbound message action.","Create a workflow rule with an outbound message action."], "answer":["Create a workflow rule with an outbound message action."] , "feedback_tf":["", ""]}
,{ "question":"Which two SOSL searches will returns records matching search criteria contained in any ofthe searchable texts fields on an object? Choose 2 answers", "choice":["[FIND 'Acme*' RETURNING Account,Opportunity];","[FIND 'Acme*' IN ANY FIELDS RETURNING Account,Opportunity];","[FIND 'Acme*' IN TEXT FIELDS RETURNING Account,Opportunity];","[FIND 'Acme*' IN ALL FIELDS RETURNING Account,Opportunity];"], "answer":["[FIND 'Acme*' RETURNING Account,Opportunity];","[FIND 'Acme*' IN ALL FIELDS RETURNING Account,Opportunity];"] , "feedback_tf":["", ""]}
,{ "question":"A developer is creating an enhancement to an application that will allow people to berelated to their employer.Which date model should be used to track the data?", "choice":["Create a junction object to relate many people to many employers trough master-detailrelationship","Create a junction object to relate many people to many employers trough lookup relationship","Create a lookup relationship to indicate that a person has an employer","Create a master detail relationship to indicate that a person has an employer"], "answer":["Create a lookup relationship to indicate that a person has an employer"] , "feedback_tf":["", ""]}
,{ "question":"Which two platform features allow for the use of unsupported languages? Choose 2answers", "choice":["Heroku Acm","App.json","Buildpacks","Docker"], "answer":["Buildpacks","Docker"] , "feedback_tf":["", ""]}
,{ "question":"A developer wants to use all of the functionality provided by the standard controller for anobject, but needs to override the Save standard action in a controller extension. Which two arerequired in the controller extension class?", "choice":["Create a method named Save with a return data type of PageReference.","Create a method that references this.superSave()","Define the class with a constructor that takes an instance of StandardController as a parameter.","Define the class with a constructor that creates a new instance of the StandardController class."], "answer":["Create a method named Save with a return data type of PageReference.","Define the class with a constructor that takes an instance of StandardController as a parameter."] , "feedback_tf":["", ""]}
,{ "question":"How should a developer prevent a recursive trigger?", "choice":["Use a  one trigger per object  pattern.","Use a static Boolean variable.","Use a trigger handler.","Use a private Boolean variable."], "answer":["Use a private Boolean variable."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to have records with specific field values in order to test a new Apexclass. What should the developer do to ensure the data is available to the test?", "choice":["Use Test.loadData() and reference a CSV file.","Use SOQL to query the org for the required data.","Use Test.loadData() and reference a static resource.","Use Anonymous Apex to create the required data."], "answer":["Use Test.loadData() and reference a static resource."] , "feedback_tf":["", ""]}
,{ "question":"Which feature allows a developer to create test records for use in test classes?", "choice":["Static resources","Documents","Httpcalloutmocks","Webservicetests"], "answer":["Webservicetests"] , "feedback_tf":["", ""]}
,{ "question":"When the value of a field of an account record is updated, which method will update thevalue of a custom field opportunity? Choose 2 answers.", "choice":["A process builder on the Account object","An Apex trigger on the Account object.","A cross-object formula field on the Account object","A workflow rule on the Account object"], "answer":["A process builder on the Account object","An Apex trigger on the Account object."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to join data received from an integration with an external system withparent records in Salesforce. The data set does not contain the Salesforce IDs of the parent records,but it does have a foreign key attribute that can be used to identify the parent.Which action will allow the developer to relate records in the data model without knowing theSalesforce ID?", "choice":["Create and populate a custom field on the parent object marked as Unique.","Create a custom field on the child object of type External Relationship.","Create and populate a custom field on the parent object marked as an External ID.","Create a custom field on the child object of type Foreign Key."], "answer":["Create a custom field on the child object of type Foreign Key."] , "feedback_tf":["", ""]}
,{ "question":"What is an accurate constructor for a custom controller named  MyController ?", "choice":["public MyController () { account = new Account () ; }","public MyController (sObject obj) { account = (Account) obj; }","public MyController (List objects) { accounts = (List ) objects; }","public MyController (ApexPages.StandardController stdController) { account = (Account)stdController.getRecord(); }"], "answer":["public MyController () { account = new Account () ; }"] , "feedback_tf":["", ""]}
,{ "question":"Which three methods help ensure quality data?", "choice":["Create a lookup filter","Adding an error to a field in before trigger","Sending an email alert using a workflow rule","Handling an exception in Apex","Adding a validation rule"], "answer":["Create a lookup filter","Sending an email alert using a workflow rule","Adding a validation rule"] , "feedback_tf":["", ""]}
,{ "question":"Where would a developer build a managed package?", "choice":["Developer Sandbox","Unlimited Edition","Partial Copy Sandbox","Developer Edition"], "answer":["Developer Edition"] , "feedback_tf":["", ""]}
,{ "question":"A developer can use the debug log to see which three types of information? Choose 3answers", "choice":["Resource usage and limits","Database changes","User login events","HTTP callout to external systems","Actions triggered by time-based workflow"], "answer":["Database changes","HTTP callout to external systems","Actions triggered by time-based workflow"] , "feedback_tf":["", ""]}
,{ "question":"Managed Packages can be created in which type of org?", "choice":["Developer Sandbox","Unlimited Edition","Developer Edition","Partial Copy Sandbox"], "answer":["Developer Edition"] , "feedback_tf":["", ""]}
,{ "question":"Which data type or collection of data types can SOQL statements populate or evaluate to?(Choose 3)", "choice":["A single sObject","An integer","A string","A list of sObjects"], "answer":["A single sObject","An integer","A list of sObjects"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers wants Opportunities to be locked from editing when reaching theClosed/Won stage.Which two strategies should a developer use to accomplish this? (Choose two.)", "choice":["Use a Visual Workflow.","Use a validation rule.","Use the Process Automation Settings.","Use a Trigger."], "answer":["Use a validation rule.","Use a Trigger."] , "feedback_tf":["", ""]}
,{ "question":"Which two sosl searches will return records matching search criteria contained in any of thesearchable text fields on an object? choose 2 answers", "choice":["[find 'acme*' in any fields returning account,opportunity]","[find 'acme*'returning account,opportunity]","[find 'acme*'in all fields returning account,opportunity]","[find 'acme*' in text fields returning account,opportunity]"], "answer":["[find 'acme*'in all fields returning account,opportunity]"] , "feedback_tf":["", ""]}
,{ "question":"How many accounts will be inserted by the following block ofcode? for(Integer i = 0 ; i ＜ 500;i++) { Account a = new Account(Name='New Account ' + i); insert a; }", "choice":["150","0","500","100"], "answer":["0"] , "feedback_tf":["", ""]}
,{ "question":"Which three process automations can immediately send an email notification to the ownerof an Opportunity when its Amount is changed to be greater than $10,000? Choose 3 answers", "choice":["Workflow Rule (Missed)","Flow Builder","Approval Process (Missed)","Process Builder (Missed)"], "answer":["Workflow Rule (Missed)","Approval Process (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"Which two queries can a developer use in a visualforce controller to protect against SOQLinjection Vulnerabilities? Choose 2 answers", "choice":["String qryName = '%' + String.enforceSecurityChecks(name)+ '%'; String qryString = 'SELECT IdFROM Contact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryName = '%' + name '%'; String qryString = 'SELECT Id FROM Contact WHERE Name LIKE:qryNAme'; List queryResults = Database.query(qryString);","String qryName = '%' + String.escpaeSingleQuotes(name)+ '%'; String qryString = 'SELECT Id FROMContact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryString = 'SELECT Id FROM Contact WHERE Name LIKE :qryNAme'; List queryResults =Database.query(qryString);"], "answer":["String qryName = '%' + String.enforceSecurityChecks(name)+ '%'; String qryString = 'SELECT IdFROM Contact WHERE Name LIKE :qryNAme'; List queryResults = Database.query(qryString);","String qryString = 'SELECT Id FROM Contact WHERE Name LIKE :qryNAme'; List queryResults =Database.query(qryString);"] , "feedback_tf":["", ""]}
,{ "question":"Where can the custom roll-up summary fields be created using Standard Objectrelationships (Choose 3)", "choice":["On Opportunity using Opportunity Product records.","On Account using Case records.","On Quote using Order records.","On Campaign using Campaign Member records.","On Account using Opportunity records."], "answer":["On Opportunity using Opportunity Product records.","On Campaign using Campaign Member records.","On Account using Opportunity records."] , "feedback_tf":["", ""]}
,{ "question":"When can a developer use a custom Visualforce page in a Force.com application? (Choose 2)", "choice":["To generate a PDF document with application data","To create components for dashboards and layouts","To deploy components between two organizations","To modify the page layout settings for a custom object"], "answer":["To generate a PDF document with application data","To create components for dashboards and layouts"] , "feedback_tf":["", ""]}
,{ "question":"What are two considerations for deciding to use a roll-up summary field? Choose 2 answer'spartner.", "choice":["Roll-up summary can be performed on formula fields, but if their formula contains an #Errorresult, it may affect the summary value.","Roll-up summary fields do not cause validation rules on the parent object unless that object isedited separately.","Roll-up cannot be performed on formula fields.","Roll-up cannot be performed on formula fields that use cross-object references or on-the-flycalculations such as NOW()."], "answer":["Roll-up summary can be performed on formula fields, but if their formula contains an #Errorresult, it may affect the summary value.","Roll-up cannot be performed on formula fields that use cross-object references or on-the-flycalculations such as NOW()."] , "feedback_tf":["", ""]}
,{ "question":"Which code segment can be used to control when the dowork() method is called?", "choice":["For (Trigger.isRunning t: Trigger.new) { dowork(); }","If(Trigger.isRunning) dowork();","For (Trigger.isInsert t: Trigger.new) { dowork(); }","If(Trigger.isInsert) dowork();"], "answer":["If(Trigger.isInsert) dowork();"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers has large number of custom applications that were built using a third-party javaScript framework and exposed using Visualforce pages. The Company wants to updatethese applications to apply styling that resembles the look and feel of Lightning Experience. Whatshould the developer do to fulfill the business request in the quickest and most effective manner?", "choice":["Incorporate the Salesforce Lightning Design System CSS stylesheet into the JavaScript applications.","Rewrite all Visualforce pages asLightning components.","Set the attribute enableLightning to treu in the definition.","Enable Available for Lightning Experience, Lightning Comminities, and the mobile app onVisualforce pages used by the custom application."], "answer":["Set the attribute enableLightning to treu in the definition."] , "feedback_tf":["", ""]}
,{ "question":"A Visualforce page is required for displaying and editing Case records that includes bothstandard and custom functionality defined in an Apex class called myControllerExtension.The Visualforce page should include which ＜apex:page＞ attribute(s) to correctly implement controllerfunctionality?", "choice":["controller= Case  and extensions= myControllerExtension ","extensions= myControllerExtension ","controller= myControllerExtension ","standardController= Case  and extensions= myControllerExtension "], "answer":["standardController= Case  and extensions= myControllerExtension "] , "feedback_tf":["", ""]}
,{ "question":"Why would a developer use Test. startTest( ) and Test.stopTest( )?", "choice":["To avoid Apex code coverage requirements for the code between these lines","To start and stop anonymous block execution when executing anonymous Apex code","To indicate test code so that it does not Impact Apex line count governor limits.","To create an additional set of governor limits during the execution of a single test class."], "answer":["To create an additional set of governor limits during the execution of a single test class."] , "feedback_tf":["", ""]}
,{ "question":"A developer wants to override a button using Visualforce on an object.What is the requirement?", "choice":["The controller or extension must have a PageReference method.","The standardController attribute must be set to the object.","The action attribute must be set to a controller method.","The object record must be instantiated in a controller or extension."], "answer":["The standardController attribute must be set to the object."] , "feedback_tf":["", ""]}
,{ "question":"Opportunity opp=[SELECT Id,StageName FROM Opportunity LIMIT 1]; Given the codeabove,how can a developer get the label for the StageName field?", "choice":["Call Opportunity.StageName.Label","Call Opportunity.StageName.getDescribe().getLabel()","Call Opp.StageName.getDescri","Call Opp.StageName.Label"], "answer":["Call Opportunity.StageName.getDescribe().getLabel()"] , "feedback_tf":["", ""]}
,{ "question":"Which two approaches optimize test maintenance and support future declarativeconfiguration changes?Choose 2 answers.", "choice":["Create a method that queries for valid records, then call this method within test methods.","Create a methods that loads valid Account records from a static resources, then call this methodwithin test methods.","Create a method that performs a callout for valid records, then call this method within testmethods.","Create a method that creates valid records,then call this method within test methods."], "answer":["Create a methods that loads valid Account records from a static resources, then call this methodwithin test methods.","Create a method that creates valid records,then call this method within test methods."] , "feedback_tf":["", ""]}
,{ "question":"A developer must modify the following code snippet to prevent the number of SOQL queriesissued from exceeding the platform governor limit. public class without sharing OpportunityService(public static List＜OpportunityLineItem＞ getOpportunityProducts(Set＜Id＞ opportunityIds){List＜OpportunitylineItem＞ oppLineItems = new List＜OpportunityLineItem＞(); for(Id thisOppId :opportunityIds){ oppLineItems.addAll([Select Id FROM OpportunityLineItems WHERE OpportunityId =:thisOppId)]; } return oppLineItems; } } The above method might be called during a trigger executionvia a Lightning component.Which technique should be implemented to avoid reaching the governor limit?", "choice":["Use the System.Limits.getQueries() method to ensure the number of queries is less than 100.","Use the System.Limits.getlimitQueries() method to ensure the number of queries is less than 100.","Refector the code above to perform the SOQL query only if the Set of opportunityIds contains less100 Ids.","Refactor the code above to perform only one SOQL query, filtering by the Set of opportunityIds."], "answer":["Use the System.Limits.getQueries() method to ensure the number of queries is less than 100."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to create a Visualforce page that will override the standard Account editbutton. The page will be used to validate the account's address using a SOQL query. The page willalso allow the user to make edits to the address. Where would the developer write the Accountaddress verification logic?", "choice":["In a Standard Extension.","In a Standard Controller.","In a Custom Controller.","In a Controller Extension."], "answer":["In a Controller Extension."] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers (UC) decided it will not to send emails to support personnel directlyfrom Salesforce in the event that an unhandled exception occurs. Instead, UC wants an externalsystem be notified of the error.What is the appropriate publish/subscribe logic to meet these requirements?", "choice":["Publish the error event using the addError() method and have the external system subscribe to theevent using CometD.","Publish the error event using the Eventbus.publish() method and have the external systemsubscribe to the event using CometD.","Have the external system subscribe to the BatchApexError event, no publishing is necessary.","Publish the error event using the addError() method and write a trigger to subscribe to the eventand notify the external system."], "answer":["Publish the error event using the Eventbus.publish() method and have the external systemsubscribe to the event using CometD."] , "feedback_tf":["", ""]}
,{ "question":"Which three statements are true regarding the @istest annotation? Choose 3 answers", "choice":["Products and pricebooks are visible in a test even if a class is annotated @istest (seealldata=false)","A method annotated @istest (seealldata=false) in a class annotated @istest (seealladata=true) hasaccess to all org data","A method annotated @istest (seealldata=true) in a class annotated @istest (seealladata=false) hasaccess to all org data","Profiles are visible in a test even if a class is annotated @istest (seealldata=false)","A class containing test methods counts toward the apex code liit regardless of any @istest annotation (Missed"], "answer":["A method annotated @istest (seealldata=false) in a class annotated @istest (seealladata=true) hasaccess to all org data","Profiles are visible in a test even if a class is annotated @istest (seealldata=false)","A class containing test methods counts toward the apex code liit regardless of any @istest annotation (Missed"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers stores Orders and Line Items in Salesforce. For security reason,financial representatives are allowed to see information on the Order such as order amount, but theyare not allowed to see the Line items on the Order. Which type of relationship should be used?", "choice":["Lookup","Direct Lookup","Indirect lookup","Master Detail"], "answer":["Master Detail"] , "feedback_tf":["", ""]}
,{ "question":"Which actions can a developer perform using the Schema Builder?Choose 2 answers", "choice":["Create a custom field and automatically add it to an existing page layout.","Create a view containing only standard and system objects.","Create a custom object and define a lookup relationship on that object","Create a view of objects and relationships without fields"], "answer":["Create a view containing only standard and system objects.","Create a custom object and define a lookup relationship on that object"] , "feedback_tf":["", ""]}
,{ "question":"Which two are best practices when it comes to component and application event handling?Choose 2 answers", "choice":["Handle low-level events in the event handler and re-fire them as higher-level events. (Missed)","Try to use application events as opposed to component events.","Use component events to communicate actions that should be handled at the application level.","Reuse the event logic in a component bundle, by putting the logic in the helper. (Missed)"], "answer":["Handle low-level events in the event handler and re-fire them as higher-level events. (Missed)","Reuse the event logic in a component bundle, by putting the logic in the helper. (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"How should a custom user interface be provided when a user edits an Account in LightningExperience?", "choice":["Override the Account's Edit button with Lightning Flow","Override the Account's Edit button with Lightning Action","Override the Account's Edit button with Lightning page.","Override the Account's Edit button with Lightning component."], "answer":["Override the Account's Edit button with Lightning component."] , "feedback_tf":["", ""]}
,{ "question":"An org has a single account named 'NoContacts' that has no related contacts. Given thequery:List＜Account＞ accounts = [Select ID, (Select ID, Name from Contacts) from Account whereName='NoContacts']; What is the result of running this Apex?", "choice":["accounts[0].contacts is invalid Apex.","accounts[0].contacts is an empty Apex.","accounts[0].contacts is Null.","A QueryException is thrown."], "answer":["accounts[0].contacts is an empty Apex."] , "feedback_tf":["", ""]}
,{ "question":"Which control statement should a developer use to ensure that a loop body executes atleast once?", "choice":["For(variable : list_or_set){}","While (condition){}","For(init_stmt;exit_cond;increment){}","Do {} while (cond)"], "answer":["Do {} while (cond)"] , "feedback_tf":["", ""]}
,{ "question":"The operation manager at a construction company uses a custom object called Machineryto manage the usage and maintenance of its cranes and other machinery. The manager wants to beable to assign machinery to different constructions jobs, and track the dates and costs associatedwith each job. More than one piece of machinery can be assigned to one construction job.What should a developer do to meet these requirements?", "choice":["Create a lookup field on the Construction Job object to the Machinery object.","Create a lookup field on the Machinery object to the Construction Job object.","Create a junction object with Master-Detail Relationship to both the Machinery object and theConstruction Job object.","Create a Master-Detail Lookup on the Machinery object to the Construction Job object."], "answer":["Create a lookup field on the Construction Job object to the Machinery object."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to prevent the creation of request records when certain conditions existin the system. A RequestLogic class exists to checks the conditions. What is the correctimplementation?", "choice":["Trigger RequestTrigger on Request (after insert) {RequestLogic.validateRecords {trigger.new};}","Trigger RequestTrigger on Request (before insert) {RequestLogic.validateRecords {trigger.new};}","Trigger RequestTrigger on Request (before insert) {if (RequestLogic.isvalid{Request})Request.addError {'Your request cannot be created at this time.'};}","Trigger RequestTrigger on Request (after insert) {if (RequestLogic.isValid{Request})Request.addError {'Your request cannot be created at this time.'};}"], "answer":["Trigger RequestTrigger on Request (before insert) {RequestLogic.validateRecords {trigger.new};}"] , "feedback_tf":["", ""]}
,{ "question":"A Hierarchy Custom Setting stores a specific URL for each profile in Salesforce. Whichstatement can a developer use to retrieve the correct URL for the current user'sprofile and displaythis on a Visualforce Page?", "choice":["{!$Setup.Url_Settings__C.Instance[Profile.Id].URL__c}","{!$Setup.Url_Settings__C.URL__c}","{!$Setup.Url_Settings__C.[Profile.Id].URL__c}","{!$Setup.Url_Settings__C.[$Profile.Id].URL__c}"], "answer":["{!$Setup.Url_Settings__C.URL__c}"] , "feedback_tf":["", ""]}
,{ "question":"What are two correct examples of the model in the salesforce MVC architecture? Choose 2answers.", "choice":["Custom field on the custom wizard_c object","Standard lightning component","Workflow rule on the contact object","Standard account lookup on the contract object"], "answer":["Standard lightning component","Workflow rule on the contact object"] , "feedback_tf":["", ""]}
,{ "question":"A developer creates an Apex Trigger with the following code block:List＜Account＞ customers= new List＜Account＞();For (Order__c o: trigger.new){Account a = [SELECT Id, Is_Customer__c FROMAccount WHERE Id =:o.Customer__c];a.Is_Customer__c = true;customers.add(a);}Database.update(customers, false);Thedeveloper tests the code using Apex Data Loader and successfully loads 10 Orders. Then, thedeveloper loads 150 Orders.How many Orders are successfully loaded when the developer attemptsto load the 150 Orders?", "choice":["0","1","150","100"], "answer":["0"] , "feedback_tf":["", ""]}
,{ "question":"What is a capability of the Force.com IDE? Choose 2 answers", "choice":["Roll back deployments.","Run Apex tests.","Download debug logs.","Edit metadata components."], "answer":["Run Apex tests.","Edit metadata components."] , "feedback_tf":["", ""]}
,{ "question":"Given the code below, what can be done so that recordcount can be accessed by a testclass, but not by a non-test class? Public class mycontroller{ private integer recordcount; }", "choice":["Add a seealldata annotation to the test class","Add the testvisible annotation to recordcount","Change recordcount from private to public","Add the testvisible annotation to the mycontroller class"], "answer":["Add the testvisible annotation to recordcount"] , "feedback_tf":["", ""]}
,{ "question":"A developer uses an 'after update' trigger on the Account object to update all the Contactsrelated to the Account. The trigger code shown below is randomly failing.List＜Contacts＞ theContacts = new List＜Contacts＞(); for(Account a : Trigger.new){ for(Contact c :[SELECT Id, Account_Date__c FROM Contact WHERE AccountId = :a.Id]){ c.Account_Date__c =Date.today(); theContacts.add(c);}} updates theContacts;Which line of code is causing the code block to fail?", "choice":["An exception is thrown if theContacts is empty","The trigger processes more than 200 records in the for loop.","An exception is thrown if Account_Date__c is null.","A SOQL query is located inside of the for loop."], "answer":["A SOQL query is located inside of the for loop."] , "feedback_tf":["", ""]}
,{ "question":"The following Apex method is part of the ContactService class that is called from a trigger:public static void setBusinessUnitToEMEA(Contact thisContact){ thisContact.Business_Unit__c = EMEA  ; update thisContact; } How should the developer modify the code to ensure best practiceare met?", "choice":["Public static void setBusinessUnitToEMEA(List＜Contact＞ contacts){for(Contact thisContact : contacts){thisContact.Business_Unit__c = 'EMEA' ;update contacts[0];}}","Public static void setBusinessUnitToEMEA(List＜Contact＞ contacts){for(Contact thisContact : contacts) {thisContact.Business_Unit__c = 'EMEA' ;}update contacts;}","Public static void setBusinessUnitToEMEA(Contact thisContact){List＜Contact＞ contacts = new List＜Contact＞();contacts.add(thisContact.Business_Unit__c = 'EMEA');update contacts;}","Public void setBusinessUnitToEMEA(List＜Contact＞ contatcs){contacts[0].Business_Unit__c = 'EMEA' ;update contacts[0];}"], "answer":["Public static void setBusinessUnitToEMEA(Contact thisContact){List＜Contact＞ contacts = new List＜Contact＞();contacts.add(thisContact.Business_Unit__c = 'EMEA');update contacts;}"] , "feedback_tf":["", ""]}
,{ "question":"A developer considers the following snippet of code: Boolean isOK; integer x; StringtheString = 'Hello'; if (isOK == false && theString == 'Hello') { x = 1; } else if (isOK == true && theString=='Hello') { x = 2; } else if (isOK != null && theString == 'Hello') { x = 3; } else { x = 4; } Based on thiscode, what is the value of x?", "choice":["2","1","3","4"], "answer":["4"] , "feedback_tf":["", ""]}
,{ "question":"How can a developer refer to, or instantiate a PageReference in Apex? Choose 2 answers", "choice":["By using a PageReference with a partial or full URL.","By using the Page object and a Visualforce page name.","By using the ApexPages.Page() method with a Visualforce page name.","By using the PageReference.Page() method with a partial or full URL."], "answer":["By using a PageReference with a partial or full URL.","By using the Page object and a Visualforce page name."] , "feedback_tf":["", ""]}
,{ "question":"What is the easiest way to verify a user before showing them sensitive content?", "choice":["Sending the user a SMS message with a passcode.","Calling the generateVerificationUrl method in apex.","Sending the user an Email message with a passcode.","Calling the Session.forcedLoginUrl method in apex."], "answer":["Calling the generateVerificationUrl method in apex."] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers implemented a private sharing model for the Account object. A customAccount search tool was developed with Apex to help sales representatives find accounts that matchmultiple criteria they specify. Since its release, users of the tool report they can see Accounts they donot own. What should the developer use to enforce sharing permission for the currently logged-inuser while using the custom search tool?", "choice":["Use the schema describe calls to determine if the logged-in users has access to the Account object.","Use the without sharing keyword on the class declaration.","Use the UserInfo Apex class to filter all SOQL queries to returned records owned by the logged-inuser.","Use the with sharing keyword on the class declaration."], "answer":["Use the schema describe calls to determine if the logged-in users has access to the Account object."] , "feedback_tf":["", ""]}
,{ "question":"A developer creates an Apex helper class to handle complex trigger logic. How can thehelper class warn users when the trigger exceeds DML governor limits?", "choice":["By using PageReference.setRedirect() to redirect the user to a custom Visualforce page before thenumber of DML statements is exceeded.","By using Messaging.sendEmail() to continue toe transaction and send an alert to the user after thenumber of DML statements is exceeded.","By using AmexMessage.Messages() to display an error message after the number of DMLstatements is exceeded.","By using Limits.getDMLRows() and then displaying an error message before the number of DMLstatements is exceeded."], "answer":["By using Limits.getDMLRows() and then displaying an error message before the number of DMLstatements is exceeded."] , "feedback_tf":["", ""]}
,{ "question":"Potential home buyers working with a real estate company can make offers on multipleproperties that are listed with the real estate company. Offer amounts can be modified; however, theproperty that has the offer cannot be modified after the offer is placed. What should be done toassociate offers with properties in the schema for the organization?", "choice":["Create a master-detail relationship in the contact object to both the property and offer customobjects","Create a lookup relationship in the property custom object to the offer custom object","Create a master-detail relationship in the offer custom object to the property custom object","Create a lookup relationship in the offer custom object to the property custom object"], "answer":["Create a master-detail relationship in the offer custom object to the property custom object"] , "feedback_tf":["", ""]}
,{ "question":"How many levels of child records can be returned in a single SOQL query from one parentobject?", "choice":["1","3","5","7"], "answer":["1"] , "feedback_tf":["", ""]}
,{ "question":"A developer declared a class as follow.public class wysiwyg { // Properties and methods including DML }Which invocation of a class method will obey the organization-wide defaults and sharing settings forthe running user in the Salesforce Organization?", "choice":["An Apex Trigger that invokes a helper method in this class","A Visualforce page with an Apex controller that invokes a method in this class","A user on an external system that has an API call into Salesforce that invokes a method in this class","A developer using the Developer Console that invokes a method in this class from the executeanonymous window"], "answer":["A developer using the Developer Console that invokes a method in this class from the executeanonymous window"] , "feedback_tf":["", ""]}
,{ "question":"What are three ways for a developer to execute tests in an org? Choose 3.", "choice":["Bulk API","ToolingAPI","Metadata API","Setup Menu"], "answer":["ToolingAPI","Metadata API","Setup Menu"] , "feedback_tf":["", ""]}
,{ "question":"Which two Apex data types can be used to reference a Salesforce record ID dynamically?(Choose two.)", "choice":["ENUM","sObject","External ID","String"], "answer":["ENUM","String"] , "feedback_tf":["", ""]}
,{ "question":"How can a developer determine, from the DescribeSObjectResult, if the current user will beable to create records for an object in Apex?", "choice":["By using the isInsertable() method.","By using the isCreatable() method.","By using the hasAccess() method.","By using the canCreate() method."], "answer":["By using the isCreatable() method."] , "feedback_tf":["", ""]}
,{ "question":"How many level of child records can be returned in a single SOQL query from one parentobject", "choice":["1","3","5","7"], "answer":["1"] , "feedback_tf":["", ""]}
,{ "question":"Which two statements are true about using the @testSetup annotation in an Apex testclass? (Choose two.)", "choice":["The @testSetup annotation cannot be used when the @isTest(SeeAllData=True) annotation isused.","Test data is inserted once for all test methods in a class.","Records created in the @testSetup method cannot be updates in individual test methods.","The @testSetup method is automatically executed before each test method in the test class isexecuted."], "answer":["The @testSetup method is automatically executed before each test method in the test class isexecuted."] , "feedback_tf":["", ""]}
,{ "question":"Where can debug log filter settings be set?Choose 2 answers", "choice":["The Filters link by the monitored user's name within the web UI.","The Show More link on the debug log's record.","On the monitored user's name.","The Log Filters tab on a class or trigger detail page."], "answer":["The Filters link by the monitored user's name within the web UI.","The Log Filters tab on a class or trigger detail page."] , "feedback_tf":["", ""]}
,{ "question":"A developer created a lightning component name accountList.cmp that display a list ofAccounts. Client-side logic that is executed when a user hovers over an account in the list should bestored in which bundle member?", "choice":["AccountListHelper.js","AccountListRenderer.js","AccountList.renderer","AccountList.helper"], "answer":["AccountList.renderer"] , "feedback_tf":["", ""]}
,{ "question":"Which two automation tools include a graphical designer? Choose 2 answers", "choice":["Approvals","Flow builder","Process builder","Workflows"], "answer":["Approvals","Flow builder"] , "feedback_tf":["", ""]}
,{ "question":"What is the result of the following code block ?Integer x = 1;Integer Y = 0;While(x ＜ 10){Y++;}", "choice":["An error occurs","Y = 9","Y = 10","X = 0"], "answer":["An error occurs"] , "feedback_tf":["", ""]}
,{ "question":"A developer executes the following query in Apex to retrieve a list of contacts for eachaccount:List＜account＞ accounts = [Select ID, Name, (Select ID, Name from Contacts) from Account] ; Whichtwo exceptions may occur when it executes? (Choose two.)", "choice":["CPU limit exception due to the complexity of the query.","SOQL query row limit exception due to the number of contacts.","SOQL query limit exception due to the number of contacts.","SOQL query row limit exception due to the number of accounts."], "answer":["SOQL query limit exception due to the number of contacts.","SOQL query row limit exception due to the number of accounts."] , "feedback_tf":["", ""]}
,{ "question":"A lead object has a custom field Prior_Email__c. The following trigger is intended to copythe current Email into the Prior_Email__c field any time the Email field is changed:Which type of exception will this trigger cause?", "choice":["A null reference exception","A compile time exception","A DML exception","A limit exception when doing a bulk update"], "answer":["A DML exception"] , "feedback_tf":["", ""]}
,{ "question":"A developer has the following requirements:Calculate the total amount on an Order.Calculate the line amount for each Line Item based on quantity selected and price.Move Line Items to a different Order if a Line Item is not stock.Which relationship implementation supports these requirements?", "choice":["Line Items has a Master-Detail field to Order and the Master can be re-parented.","Line Item has a Lookup field to Order and there can be many Line Items per Order","Order has a Lookup field to Line Item and there can be many Line Items per Order.","Order has a Master-Detail field to Line Item and there can be many Line Items per Order."], "answer":["Line Items has a Master-Detail field to Order and the Master can be re-parented."] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of the Lightning Component framework?Choose 3 answers", "choice":["It uses client-side Apex controllers for logic.","It uses a traditional publish-subscribe model.","It uses an event-driven architecture","It uses an MVC architectural design pattern."], "answer":["It uses a traditional publish-subscribe model.","It uses an event-driven architecture","It uses an MVC architectural design pattern."] , "feedback_tf":["", ""]}
,{ "question":"Which resource can be included in a Lightning Component bundle?Choose 2 answers", "choice":["Apex class","Adobe Flash","JavaScript","Documentation"], "answer":["JavaScript","Documentation"] , "feedback_tf":["", ""]}
,{ "question":"A developer executes the following code in the Developer Console:List＜Account＞ fList = new List ＜Account＞ ();For(integer i= 1; I ＜= 200; i++){fList.add(new Account (Name= 'Universal Account ' + i));}Insert fList;List ＜Account＞ sList = new List＜Account＞();For (integer I = 201;I＜=20000; i ++){sList.add(new Account (Name = 'Universal Account ' + i));}Insert sList;How manyaccounts are created in the Salesforce organization ?", "choice":["20000","0","200","1000"], "answer":["0"] , "feedback_tf":["", ""]}
,{ "question":"Given the code below, which three statements can be used to create the controllervariable? Public class accountlistcontroller{ public list＜account＞getaccounts(){ returncontroller.getrecords(); } } Choose 3 answers", "choice":["Apexpages.standardsetcontroller controller=newapexpages.standardsetcontroller(database.getquerylocator('select id from account'));","Apexpages.standardcontroller controller= new apexpages.standardcontroller([select id fromaccount]);","Apexpages.standardcontroller controller= newapexpages.standardcontroller(database.getquerylocator('select id from account'));","Apexpages.standardsetcontroller controller = new apexpages.standardsetcontroller(database.query('select id from account'));","Apexpages.standardsetcontroller controller = new apexpages.standardsetcontroller(database.getquerylocator([select id from account]));"], "answer":["Apexpages.standardcontroller controller= new apexpages.standardcontroller([select id fromaccount]);","Apexpages.standardsetcontroller controller = new apexpages.standardsetcontroller(database.query('select id from account'));","Apexpages.standardsetcontroller controller = new apexpages.standardsetcontroller(database.getquerylocator([select id from account]));"] , "feedback_tf":["", ""]}
,{ "question":"Which three declarative fields are correctly mapped to variable types in Apex? (Choosethree.)", "choice":["Number maps to Decimal.","Number maps to Integer.","TextArea maps to List of type String.","Date/Time maps to Dateline.","Checkbox maps to Boolean."], "answer":["Number maps to Decimal.","Date/Time maps to Dateline.","Checkbox maps to Boolean."] , "feedback_tf":["", ""]}
,{ "question":"When creating a record with a Quick Action, what is the easiest way to post a feed item?", "choice":["By selecting create feed item on the quick action.","By adding a trigger on the new record.","By adding a workflow rule on the new record.","By selecting create case feed on the new record."], "answer":["By selecting create feed item on the quick action."] , "feedback_tf":["", ""]}
,{ "question":"Which two are true regarding a Dyno? Choose 2 answers", "choice":["Is a light weight VM used to run code on the Heroku Platform","Has the ability to sleep as a standard and performance Dyno","Is a lightweight Linux container used in a collection to run Heroku applications","Has Ephemeral filesystems and is rebooted every 24 hours."], "answer":["Is a lightweight Linux container used in a collection to run Heroku applications","Has Ephemeral filesystems and is rebooted every 24 hours."] , "feedback_tf":["", ""]}
,{ "question":"How can a developer get all of the available record types for the current user on the caseobject?", "choice":["Use SOQL to get all cases","Use describesobjectresult of the case object","Use case.getrecordtypes()","Use describefieldresult of the case.recordtype field"], "answer":["Use describefieldresult of the case.recordtype field"] , "feedback_tf":["", ""]}
,{ "question":"What is a benefit of using a trigger framework?", "choice":["Simplifies addition of context-specific logic","Increases trigger governor limits","Allows functional code to be tested b","Reduces trigger execution time"], "answer":["Reduces trigger execution time"] , "feedback_tf":["", ""]}
,{ "question":"The account object has a custom percent field, rating, defined with a length of 2 with 0decimal places. An account record has the value of 50% in its rating field and is processed in the apexcode below after being retrieved from the database with SOQL public void processaccount(){ decimalacctscore = acc.rating__c *100; } what is the value of acctscore after this code executes?", "choice":["5","50","500","5000"], "answer":["500"] , "feedback_tf":["", ""]}
,{ "question":"Which requirement needs to be implemented by using standard workflow instead ofProcess Builder? Choose2 answers", "choice":["Create activities at multiple intervals.","Send an outbound message without Apex code.","Copy an account address to its contacts.","Submit a contract for approval."], "answer":["Send an outbound message without Apex code.","Copy an account address to its contacts."] , "feedback_tf":["", ""]}
,{ "question":"In order to override a standard action with a visualforce page, which attribute must bedefined in the＜apex:page＞ tag?", "choice":["Pagereference","Override","Standardcontroller","Controller"], "answer":["Standardcontroller"] , "feedback_tf":["", ""]}
,{ "question":"A developer is debugging the following code to determinate why Accounts are not beingcreated Account a = new Account(Name = 'A'); Database.insert(a, false); How should the code bealtered to help debug the issue?", "choice":["Add a System.debug() statement before the insert method","Add a try/catch around the insert method","Set the second insert method parameter to TRUE","Collect the insert method return value a Saveresult record"], "answer":["Collect the insert method return value a Saveresult record"] , "feedback_tf":["", ""]}
,{ "question":"A developer creates a method in an Apex class and needs to ensure that errors are handledproperly.What would the developer use? (There are three correct answers.)", "choice":["ApexPages.addErrorMessage()","A custom exception",".addError()","Database.handleException()","A try/catch construct"], "answer":["A custom exception",".addError()","A try/catch construct"] , "feedback_tf":["", ""]}
,{ "question":"What is true of a partial sandbox that is not true of a full sandbox? Choose 2 answers", "choice":["More frequent refreshes","Limited to 5 GB of data","Use of change sets","Only includes necessary meta data"], "answer":["More frequent refreshes","Limited to 5 GB of data"] , "feedback_tf":["", ""]}
,{ "question":"Which two ways can a developer instantiate a PageReference in Apex? Choose 2 answers", "choice":["By using an object standard set controller action","By using ApexPages.currentPage()","By using the PageReference.getURL() method","By using an object standard controller action"], "answer":["By using an object standard set controller action","By using the PageReference.getURL() method"] , "feedback_tf":["", ""]}
,{ "question":"When would a developer use a custom controller instead of a controller extension? Choose2 answers:", "choice":["When a Visualforce page needs to replace the functionality of a standard controller.","When a Visualforce page does not reference a single primary object.","When a Visualforce page should not enforce permissions or field-level security.","When a Visualforce page needs to add new actions to a standard controller."], "answer":["When a Visualforce page does not reference a single primary object.","When a Visualforce page should not enforce permissions or field-level security."] , "feedback_tf":["", ""]}
,{ "question":"What is the order of operations when a record is saved in Salesforce?", "choice":["Process flows, triggers, workflow, commit","Workflow, process flows, triggers, commit","Workflow, triggers, process flows, commit","Triggers, workflow, process flows, commit"], "answer":["Triggers, workflow, process flows, commit"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to provide a way to mass edit,update, and delete records from a list viewin which two ways can this be accomlpished? choose 2 answers", "choice":["Download an unmanaged package from the appexchange that provides customizable mass edit,update and delete functionality","Configure the user interface and enable both inline editing enhanced lists","Download a managed package from the appexchange that provides customizable enhanced listviews and buttons","Create a new visualforce page and apex controller for the list view that provides mass edit,updateand delete functionality"], "answer":["Download a managed package from the appexchange that provides customizable enhanced listviews and buttons","Create a new visualforce page and apex controller for the list view that provides mass edit,updateand delete functionality"] , "feedback_tf":["", ""]}
,{ "question":"Given:Map＜ID, Account＞ accountMap = new Map＞ID, Account＞ ([SELECT Id, Name FROM Account]); Whatare three valid Apex loop structures for iterating through items in the collection? (Choose three.)", "choice":["for (ID accountID : accountMap.keySet()) {...}","for (Account accountRecord : accountMap.values()) {...}","for (Integer i=0; I ＜ accountMap.size(); i++) {...}","for (ID accountID : accountMap) {...}"], "answer":["for (ID accountID : accountMap.keySet()) {...}","for (Account accountRecord : accountMap.values()) {...}","for (Integer i=0; I ＜ accountMap.size(); i++) {...}"] , "feedback_tf":["", ""]}
,{ "question":"A developer wrote Apex code that calls out to an external system. How should a developerwrite the test to provide test coverage?", "choice":["Write a class that extends HTTPCalloutMock.","Write a class that implements the HTTPCalloutMock interface.","Write a class that implements the WebserviceMock interface.","Write a class that extends WebserviceMock"], "answer":["Write a class that implements the HTTPCalloutMock interface."] , "feedback_tf":["", ""]}
,{ "question":"Which two combined methods should a developer use to prevent more than one openOpportunity on each Account? Choose 2 answers", "choice":["Create an Account Roll-up Summary field to count open Opportunities","Create an Opportunity Validation Rule to generate an error on insert","Create an Account Trigger to generate an error on Opportunity insert","Create an Opportunity Workflow Rule to auto-close the Opportunity"], "answer":["Create an Account Roll-up Summary field to count open Opportunities","Create an Opportunity Validation Rule to generate an error on insert"] , "feedback_tf":["", ""]}
,{ "question":"A developer creates a custom controller and custom Visualforce page by using the followingcode block:public class myController {public String myString;public String getMyString() {return'getmyString';}public String getStringMethod1() {return myString;}public String getStringMethod2() {if(myString == null)myString ='Method2';return myString;}}{!myString}, {!StringMethod1}, {!StringMethod2}, {!myString}What doesthe user see when accessing the custom page?", "choice":["GetMyString , , Method2 , getMystring",", , Method2 , getMyString",", , Method2,","GetMyString , , ,"], "answer":["GetMyString , , Method2 , getMystring"] , "feedback_tf":["", ""]}
,{ "question":"A platform developer at Universal Containers needs to create a custom button for theAccount object that, when clicked, will perform a series of calculations and redirect the user to acustom Visualforce page.Which three attributes need to be defined with values in the ＜apex:page＞ tag to accomplish this?(Choose three.)", "choice":["action","renderAs","standardController","readOnly"], "answer":["action","renderAs","standardController"] , "feedback_tf":["", ""]}
,{ "question":"The sales team at universal container would like to see a visual indicator appear on bothaccount and opportunity page layout to alert salespeople when an account is late making paymentsor has entered the collections process. What can a developer implement to achieve this requirementwithout having to write custom code?", "choice":["Workflow rule","Formula field","Roll-up summary field","Quick action"], "answer":["Formula field"] , "feedback_tf":["", ""]}
,{ "question":"How can a developer warn users of SOQL governor limit violations in a trigger?", "choice":["Use ApexMessage.Message() to display an error message after the number of SOQL queriesexceeds the limit.","Use PageReference.setRedirect() to redirect the user to a custom Visualforce page before thenumber of SOQL queries exceeds the limit.","Use Messaging.SendEmail() to continue the transaction and send an alert to the user after thenumber of SOQL queries exceeds the limit.","Use Limits.getQueries() and display an error message before the number of SOQL queries exceedsthe limit."], "answer":["Use Limits.getQueries() and display an error message before the number of SOQL queries exceedsthe limit."] , "feedback_tf":["", ""]}
,{ "question":"Which option would a developer use to display the Accounts created in the current weekand the number of related Contacts using a debug statement in Apex?", "choice":["For(Account acc: [SELECT Id, Name,(SELECT Id, Name FROM Contacts) FROM Account WHERECreatedDate = THIS_WEEK]) { List cons = acc.Contacts; System.debug(acc.Name + ' has ' + cons.size()+ 'Contacts'; }","For(Account acc: [SELECT Id, Name, (SELECT Id, Name FROM Contacts) FROM Account WHERECreatedDate = CURRENT_WEEK]){ List cons = acc.Contacts; System.debug(acc.Name + ' has ' +cons.size() + 'Contacts'); }","For(Account acc:[SELECT Id, Name, Account.Contacts FROM Account WHERE CreatedDate =CURRENT_WEEK]) { List cons = acc.Account.Contacts; System.debug(acc.Name + ' has ' + cons.size() +'Contacts'); }","For(Account acc: [SELECT Id, Name, Account.Contacts FROM Account WHERE CreatedDate =THIS_WEEK]){ List cons = acc.Account.Contacts; System.debug(acc.Name + ' has ' + cons.size() +'Contacts' }"], "answer":["For(Account acc: [SELECT Id, Name,(SELECT Id, Name FROM Contacts) FROM Account WHERECreatedDate = THIS_WEEK]) { List cons = acc.Contacts; System.debug(acc.Name + ' has ' + cons.size()+ 'Contacts'; }"] , "feedback_tf":["", ""]}
,{ "question":"A developer must create a CreditcardPayment class that provides an implementation of anexisting Payment class. Public virtual class Payment { public virtual void makePayment(Decimalamount) { /*implementation*/} } Which is the correct implementation?", "choice":["Public class CreditcardPayment extends Payment {public override void makePayment(Decimal amount) { /*implementation*/ }}","Public class CreditCardPayment implements Payment {public virtual void makePayment(Decimal amount) { /*implementation*/ }}","Public class CreditCardPayment extends Payment {public virtual void makePayment(Decimal amount) { /*implementation*/ }}","Public class CreditCardPayment implements Payment {public override void makePayment(Decimal amount) { /*Implementation*/ }}"], "answer":["Public class CreditcardPayment extends Payment {public override void makePayment(Decimal amount) { /*implementation*/ }}"] , "feedback_tf":["", ""]}
,{ "question":"Which two queries can a developer use in a Visualforce controller to protect against SOQLinjection vulnerabilities? Choose 2 answers", "choice":["String qryName = % + String.enforceSecurityChecks(name)+ % ;String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ;List queryResults = Database.query(qryString);","String qryName = % + name % ;String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ;List queryResults = Database.query(qryString);","String qryName = % + String.escapeSingleQuotes(name)+ % ;String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ;List queryResults = Database.query(qryString);","String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ; List queryResults =Database.query(qryString);"], "answer":["String qryName = % + name % ;String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ;List queryResults = Database.query(qryString);","String qryName = % + String.escapeSingleQuotes(name)+ % ;String qryString = SELECT Id FROM Contact WHERE Name LIKE :qryNAme ;List queryResults = Database.query(qryString);"] , "feedback_tf":["", ""]}
,{ "question":"A developer writes a trigger on the Account object on the before update event thatincrements a count field. A workflow rule also increments the count field every time that an Accountis created or update. The field update in the workflow rule is configured to not re-evaluate workflowrules. What is the value of the count field if an Account is inserted with an initial value of zero,assuming no other automation logic is implemented on the Account?", "choice":["3","2","1","4"], "answer":["3"] , "feedback_tf":["", ""]}
,{ "question":"For which example task should a developer use a trigger rather than a workflow rule?", "choice":["To set the primary Contact on an Account record when it is saved","To send an email to hiring manager when a candidate accepts a job offer.","To set the Name field of an expense report record to Expense and the Date when it is saved.","To notify an external system that a record has been modified."], "answer":["To set the primary Contact on an Account record when it is saved"] , "feedback_tf":["", ""]}
,{ "question":"In Lightning component framework, which resource can be used to fire events? Choose 2answers.", "choice":["Third-party Javascript code","Javascript controller actions","Visualforce controller actions","Third-party web service code"], "answer":["Third-party Javascript code","Javascript controller actions"] , "feedback_tf":["", ""]}
,{ "question":"A developer wants multiple test classes to use the same set of test data. How should thedeveloper create the test data?", "choice":["Define a variable for test records in each test classes","Create a test setup method for each test class","Use the seealldata=true annotation in each test class","Reference a test utility class in each test class"], "answer":["Use the seealldata=true annotation in each test class"] , "feedback_tf":["", ""]}
,{ "question":"custom picklist field, Food_Preference__c, exist on a custom object. The picklist contains thefollowing options: 'Vegan','Kosher','No Preference'. The developer must ensure a value is populatedevery time a record is created or updated. What is the most efficient way to ensure a value isselected every time a record is saved?", "choice":["Set  Use the first value in the list as the default value  as True.","Set a validation rule to enforce a value is selected.","Mark the field as Required on the field definition.","Mark the field as Required on the object's page layout."], "answer":["Mark the field as Required on the field definition."] , "feedback_tf":["", ""]}
,{ "question":"A developer is tasked to perform a security review of the ContactSearch Apex class thatexists in the system.Whithin the class, the developer identifies the following method as a security threat: List＜Contact＞performSearch(String lastName){ return Database.query('Select Id, FirstName, LastName FROMContact WHERE LastName Like %'+lastName+'%); } What are two ways the developer can update themethod to prevent a SOQL injection attack? Choose 2 answers", "choice":["Use variable binding and replace the dynamic query with a static SOQL. (Missed)","Use the escapeSingleQuote method to sanitize the parameter before its use. (Missed)","Use a regular expression expression on the parameter to remove special characters.","Use the @Readonly annotation and the with sharing keyword on the class."], "answer":["Use a regular expression expression on the parameter to remove special characters.","Use the @Readonly annotation and the with sharing keyword on the class."] , "feedback_tf":["", ""]}
,{ "question":"A developer created a visualforce page using a custom controller that calls an apex helperclass. A method in the helper class hits a governor limit. what is the result of the transaction?", "choice":["The helper class creates a savepoint and continues","All changes in the transaction are rolled back","All changes made by the custom controller are saved","The custom controller calls the helper class method ag"], "answer":["All changes made by the custom controller are saved"] , "feedback_tf":["", ""]}
,{ "question":"In which two org types can a developer create new Apex Classes? Choose 2 answers", "choice":["Developer Edition","Sandbox","Enterprise Edition","Unlimited"], "answer":["Developer Edition","Sandbox"] , "feedback_tf":["", ""]}
,{ "question":"What can used to delete components from production?", "choice":["A change set deployment with the delete option checked","An ant migration tool deployment with destructivechanges xml file and the components to deletein the package .xml file","A change set deployment with a destructivechanges XML file","An ant migration tool deployment with a destructivechanges XML file and an empty package .xmlfile"], "answer":["An ant migration tool deployment with a destructivechanges XML file and an empty package .xmlfile"] , "feedback_tf":["", ""]}
,{ "question":"Which standard field needs to be populated when a developer inserts new Contact recordsprogrammatically?", "choice":["Accountld","Name","LastName","FirstName"], "answer":["LastName"] , "feedback_tf":["", ""]}
,{ "question":"How can a developer use a Set＜Id＞ to limit the number of records returned by a SOQLquery?", "choice":["Reference the Set in the LIMIT clause of the query","Pass the query results as an argument in a reference to the Set.containsAll() method.","Pass the Set as an argument in a reference to the Database.query() method","Reference the Set in the WHERE clause of the query"], "answer":["Reference the Set in the WHERE clause of the query"] , "feedback_tf":["", ""]}
,{ "question":"A developer is creating a Visualforce page that allows users to create multipleOpportunities. The developer is asked to verify the current user's default Opportunity record type,and set certain default values based on the record type before inserting the record. How can thedeveloper find the current user's default record type?", "choice":["Use the Schema.userInfo.Opportunity.getDefaultRecordType() method.","Create the opportunity and check the opportunity.recordType before inserting, which will havethe record ID of the current user's default record type","Query the Profile where the ID equals userInfo.getProfileID() and then use theprofile.Opportunity.getDefaultRecordType() method.","Use Opportunity.SObjectType.getDescribe().getRecordTypeInfos() to get a list of record types, anditerate trought them until isdefaultRecordTypeMapping() is true."], "answer":["Use Opportunity.SObjectType.getDescribe().getRecordTypeInfos() to get a list of record types, anditerate trought them until isdefaultRecordTypeMapping() is true."] , "feedback_tf":["", ""]}
,{ "question":"What is a valid way of loading external JavaScript files into a Visualforce page? (Choose 2)", "choice":["Using an (apex:includeScript)* tag. \＞","Using an (apex:define)* tag.","Using a (link)* tag.","Using a (script)* tag."], "answer":["Using an (apex:includeScript)* tag. \＞","Using a (script)* tag."] , "feedback_tf":["", ""]}
,{ "question":"A Visual force page displays two fields named Phone Number and Email.User1 has access toPhone Number, but not to Email.User2 has access to Email, but not Phone NumberA developer needsto ensure that User1 can only see Phone Number, and User2 can only see Email.Which method canthe developer use to achieve this?", "choice":["Schema isUpdateable() method.","Schema isAccessible() method.","Schema isReadable() method.","Schema isCreateable() method."], "answer":["Schema isAccessible() method."] , "feedback_tf":["", ""]}

]}
