var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"What is true of a partial sandbox that is not true of a full sandbox? Choose 2 answers", "choice":["More frequent refreshes","Limited to 5 GB of data","Use of change sets","Only includes necessary meta data"], "answer":["More frequent refreshes","Limited to 5 GB of data"] , "feedback_tf":["", ""]}
,{ "question":"Which two ways can a developer instantiate a PageReference in Apex? Choose 2 answers", "choice":["By using an object standard set controller action","By using ApexPages.currentPage()","By using the PageReference.getURL() method","By using an object standard controller action"], "answer":["By using an object standard set controller action","By using the PageReference.getURL() method"] , "feedback_tf":["", ""]}
,{ "question":"When would a developer use a custom controller instead of a controller extension? Choose2 answers:", "choice":["When a Visualforce page needs to replace the functionality of a standard controller.","When a Visualforce page does not reference a single primary object.","When a Visualforce page should not enforce permissions or field-level security.","When a Visualforce page needs to add new actions to a standard controller."], "answer":["When a Visualforce page does not reference a single primary object.","When a Visualforce page should not enforce permissions or field-level security."] , "feedback_tf":["", ""]}
,{ "question":"What is the order of operations when a record is saved in Salesforce?", "choice":["Process flows, triggers, workflow, commit","Workflow, process flows, triggers, commit","Workflow, triggers, process flows, commit","Triggers, workflow, process flows, commit"], "answer":["Triggers, workflow, process flows, commit"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to provide a way to mass edit,update, and delete records from a list viewin which two ways can this be accomlpished? choose 2 answers", "choice":["Download an unmanaged package from the appexchange that provides customizable mass edit,update and delete functionality","Configure the user interface and enable both inline editing enhanced lists","Download a managed package from the appexchange that provides customizable enhanced listviews and buttons","Create a new visualforce page and apex controller for the list view that provides mass edit,updateand delete functionality"], "answer":["Download a managed package from the appexchange that provides customizable enhanced listviews and buttons","Create a new visualforce page and apex controller for the list view that provides mass edit,updateand delete functionality"] , "feedback_tf":["", ""]}
,{ "question":"Given:Map＜ID, Account＞ accountMap = new Map＞ID, Account＞ ([SELECT Id, Name FROM Account]); Whatare three valid Apex loop structures for iterating through items in the collection? (Choose three.)", "choice":["for (ID accountID : accountMap.keySet()) {...}","for (Account accountRecord : accountMap.values()) {...}","for (Integer i=0; I ＜ accountMap.size(); i++) {...}","for (ID accountID : accountMap) {...}"], "answer":["for (ID accountID : accountMap.keySet()) {...}","for (Account accountRecord : accountMap.values()) {...}","for (Integer i=0; I ＜ accountMap.size(); i++) {...}"] , "feedback_tf":["", ""]}
,{ "question":"A developer wrote Apex code that calls out to an external system. How should a developerwrite the test to provide test coverage?", "choice":["Write a class that extends HTTPCalloutMock.","Write a class that implements the HTTPCalloutMock interface.","Write a class that implements the WebserviceMock interface.","Write a class that extends WebserviceMock"], "answer":["Write a class that implements the HTTPCalloutMock interface."] , "feedback_tf":["", ""]}
,{ "question":"Which two combined methods should a developer use to prevent more than one openOpportunity on each Account? Choose 2 answers", "choice":["Create an Account Roll-up Summary field to count open Opportunities","Create an Opportunity Validation Rule to generate an error on insert","Create an Account Trigger to generate an error on Opportunity insert","Create an Opportunity Workflow Rule to auto-close the Opportunity"], "answer":["Create an Account Roll-up Summary field to count open Opportunities","Create an Opportunity Validation Rule to generate an error on insert"] , "feedback_tf":["", ""]}
,{ "question":"A developer creates a custom controller and custom Visualforce page by using the followingcode block:public class myController {public String myString;public String getMyString() {return'getmyString';}public String getStringMethod1() {return myString;}public String getStringMethod2() {if(myString == null)myString ='Method2';return myString;}}{!myString}, {!StringMethod1}, {!StringMethod2}, {!myString}What doesthe user see when accessing the custom page?", "choice":["GetMyString , , Method2 , getMystring",", , Method2 , getMyString",", , Method2,","GetMyString , , ,"], "answer":["GetMyString , , Method2 , getMystring"] , "feedback_tf":["", ""]}
,{ "question":"A platform developer at Universal Containers needs to create a custom button for theAccount object that, when clicked, will perform a series of calculations and redirect the user to acustom Visualforce page.Which three attributes need to be defined with values in the ＜apex:page＞ tag to accomplish this?(Choose three.)", "choice":["action","renderAs","standardController","readOnly"], "answer":["action","renderAs","standardController"] , "feedback_tf":["", ""]}
]}
