var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"A company wants to create an employee rating program that allows employees to rate eachother. An employees average rating must be displayed on the employee record. Employees must beable to create rating records, but are not allowed to create employee records. Which two actionsshould a developer take to accomplish this task?", "choice":["Create a trigger on the Rating object than updates a field on the Employee object.","Create a roll-up summary field on the Employee and use AVG to calculate the average rating score.","Create a lookup relationship between the Rating and Employee object.","Create a master-detail relationship between the Rating and Employee objects."], "answer":["Create a roll-up summary field on the Employee and use AVG to calculate the average rating score."] , "feedback_tf":["", ""]}
,{ "question":"Candidates are reviewed by four separate reviewers and their comments and scores whichrange from 1 (lowest) to 5 (highest) are stored on a review record that is a detail record for acandidate what is the best way to indicate that a combined review score of 15 of better is required torecommend that the candidate come in for an interview?", "choice":["Use a validation rule on a total score field on the candidate record that prevents a recommendedfield from being true if the total score is less than 15","Use a workflow rule to calculate the sum of the review scores and send an email to the hiringmanager when the total is 15 or better","Use visual workflow to set a recommended field on the candidate whenever the cumulativereview score is 15 or better","Use a rollup summary field to calculates the sum of the review scores, and store this in a totalscore field on the candidate"], "answer":["Use a workflow rule to calculate the sum of the review scores and send an email to the hiringmanager when the total is 15 or better"] , "feedback_tf":["", ""]}
,{ "question":"A developer is asked to create a PDF quote document formatted using the company'sbranding guidelines, and automatically save it to the Opportunity record.Which two ways should a developer create this functionality? (Choose two.)", "choice":["Install an application from the AppExchange to generate documents.","Create a Visualforce page with custom styling.","Create an email template and use it in Process Builder.","Create a visual flow that implements the company's formatting."], "answer":["Install an application from the AppExchange to generate documents.","Create a Visualforce page with custom styling."] , "feedback_tf":["", ""]}
,{ "question":"Which statement is true about a hierarchical relationship as it pertains to user records?", "choice":["It uses a junction object and lookup relationships to allow many user records to be related tomany other user records","It uses a junction object and master-detail relationship to allow many user records to be related tomany other user records","It uses a master-detail relationship to allow one user record to be related to another user record","It uses a special lookup relationship to allow one user record to be related to another user record"], "answer":["It uses a special lookup relationship to allow one user record to be related to another user record"] , "feedback_tf":["", ""]}
,{ "question":"Which statement results in an Apex compiler error?", "choice":["Map＜Id,Leas＞ lmap = new Map＜Id,Lead＞([Select ID from Lead Limit 8]);","Date d1 = Date.Today(), d2 = Date.ValueOf('2018-01-01');","Integer a=5, b=6, c, d = 7;","List＜string＞ s = List＜string＞{'a','b','c');"], "answer":["List＜string＞ s = List＜string＞{'a','b','c');"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to create a Visualforce page that displays Case data. The page will beused by both support reps and support managers. The Support Rep profile does not allow visibility ofthe Customer_Satisfaction__c field, but the Support Manager profile does.How can the developer create the page to enforce Field Level Security and keep future maintenanceto a minimum?", "choice":["Create one Visualforce Page for use by both profiles.","Use a new Support Manager permission set.","Create a separate Visualforce Page for each profile.","Use a custom controller that has the with sharing keywords."], "answer":["Use a custom controller that has the with sharing keywords."] , "feedback_tf":["", ""]}
,{ "question":"A company that uses a Custom object to track candidates would like to send candidateinformation automatically to a third -party human resource system when a candidate is hired. Whatcan a developer do to accomplish this task?", "choice":["Create an escalation rule to the hiring manager.","Create an auto response rule to the candidate.","Create a Process Builder with an outbound message action.","Create a workflow rule with an outbound message action."], "answer":["Create a workflow rule with an outbound message action."] , "feedback_tf":["", ""]}
,{ "question":"Which two SOSL searches will returns records matching search criteria contained in any ofthe searchable texts fields on an object? Choose 2 answers", "choice":["[FIND 'Acme*' RETURNING Account,Opportunity];","[FIND 'Acme*' IN ANY FIELDS RETURNING Account,Opportunity];","[FIND 'Acme*' IN TEXT FIELDS RETURNING Account,Opportunity];","[FIND 'Acme*' IN ALL FIELDS RETURNING Account,Opportunity];"], "answer":["[FIND 'Acme*' RETURNING Account,Opportunity];","[FIND 'Acme*' IN ALL FIELDS RETURNING Account,Opportunity];"] , "feedback_tf":["", ""]}
,{ "question":"A developer is creating an enhancement to an application that will allow people to berelated to their employer.Which date model should be used to track the data?", "choice":["Create a junction object to relate many people to many employers trough master-detailrelationship","Create a junction object to relate many people to many employers trough lookup relationship","Create a lookup relationship to indicate that a person has an employer","Create a master detail relationship to indicate that a person has an employer"], "answer":["Create a lookup relationship to indicate that a person has an employer"] , "feedback_tf":["", ""]}
,{ "question":"Which two platform features allow for the use of unsupported languages? Choose 2answers", "choice":["Heroku Acm","App.json","Buildpacks","Docker"], "answer":["Buildpacks","Docker"] , "feedback_tf":["", ""]}
]}
