var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"A developer in a Salesforce org with 100 Accounts executes the following code using theDeveloper console:Account myAccount = new Account(Name = 'MyAccount');Insert myAccount;For(Integer x = 0; x ＜150; x++){Account newAccount = new Account (Name='MyAccount' + x);try {Insert newAccount;} catch(Exception ex) {System.debug (ex) ;}}insert new Account (Name='myAccount');How many accountsare in the org after this code is run?", "choice":["101","100","102","252"], "answer":["100"] , "feedback_tf":["", ""]}
,{ "question":"Which action can a developer perform in a before update trigger? (Choose 2)", "choice":["Display a custom error message in the application interface.","Change field values using the Trigger.new context variable.","Delete the original object using a delete DML operation.","Update the original object using an update DML operation."], "answer":["Display a custom error message in the application interface.","Change field values using the Trigger.new context variable."] , "feedback_tf":["", ""]}
,{ "question":"Which two roll-up summary field types are required to find the average of values on detailrecords in a Master-Detail relationship?", "choice":["Roll-up summary field of type COUNT","Roll-up summary field of type SUM","Roll-up summary field of type NUM","Roll-up summary field of type TOTAL"], "answer":["Roll-up summary field of type COUNT","Roll-up summary field of type SUM"] , "feedback_tf":["", ""]}
,{ "question":"What is the data type returned by the following SOSL search? {FIND 'Acme*' in name fieldsreturning account,opportunity};", "choice":["List＜List＜Account＞,List＜Opportunity＞","Map＜sObject,sObject＞","Map＜Id,sObject＞","List＜List＜sObject＞＞"], "answer":["List＜List＜sObject＞＞"] , "feedback_tf":["", ""]}
,{ "question":"A candidate may apply to multiple jobs at the company Universal Containers by submtting asingle application per job posting. Once an application is submitted for a job posting, that applicationcannot be modified to be resubmitted to a different job posting.What can the administrator do toassociate an application with each job posting in the schema for the organization?", "choice":["Create a master-detail relationship in the Job Postings custom object to the Applications customobject.","Create a master-detail relationship in the Application custom object to the Job Postings customobject.","Create a lookup relationship on both objects to a junction object called Job Posting Applications.","Create a lookup relationship in the Applications custom object to the Job Postings custom object"], "answer":["Create a master-detail relationship in the Job Postings custom object to the Applications customobject."] , "feedback_tf":["", ""]}
,{ "question":"Which declarative method helps ensure quality data? (Choose 3)", "choice":["Validation Rules","Workflow alerts","Exception Handling","Lookup Filters","Page Layouts"], "answer":["Validation Rules","Lookup Filters","Page Layouts"] , "feedback_tf":["", ""]}
,{ "question":"A developer writes a SOQL query to find child records for a specific parent. How many levelscan be returned in a single query?", "choice":["1","7","5","3"], "answer":["5"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to create an audit trail for records that are sent to the recycle bin. Whichtype of trigger is most appropriate to create?", "choice":["Before delete","After undelete","After delete","Before undelete"], "answer":["After undelete"] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to update an unrelated object when a record gets saved. Which twotrigger types should the developer create?", "choice":["After insert","After update","Before update","Before insert"], "answer":["Before update","Before insert"] , "feedback_tf":["", ""]}
,{ "question":"A developer created a Visualforce page with a custom controller to show a list of accounts.The page uses the＜apex:SelecList＞ component, with a variable called  selection , to show the valid values forAccount.Type.The page uses an ＜apex:pageBlockTable＞ component to display the list of accounts, where theiteration variable is  acct . The developer wants to ensure that when a user selects a type on the＜apex : selectList＞ component, only accounts with that type are shown on the page. What should thedeveloper do to accomplish this?", "choice":["Use the onChange event to update the list of accounts in the controller when the value changes,and then re-render the pageBlockTable.","Create multiple lists in the controller that represent the relevant accounts for each account typewhen the page loads, then reference the correct one dynamically on the pageBlockTable.","Add the Rendered={!Acct.type==selection} attribute to the pageBlockTable component","Create a component for each option and use a variable with hide parameter on the element."], "answer":["Use the onChange event to update the list of accounts in the controller when the value changes,and then re-render the pageBlockTable."] , "feedback_tf":["", ""]}
]}
