var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"A developer wants to use all of the functionality provided by the standard controller for anobject, but needs to override the Save standard action in a controller extension. Which two arerequired in the controller extension class?", "choice":["Create a method named Save with a return data type of PageReference.","Create a method that references this.superSave()","Define the class with a constructor that takes an instance of StandardController as a parameter.","Define the class with a constructor that creates a new instance of the StandardController class."], "answer":["Create a method named Save with a return data type of PageReference.","Define the class with a constructor that takes an instance of StandardController as a parameter."] , "feedback_tf":["", ""]}
,{ "question":"How should a developer prevent a recursive trigger?", "choice":["Use a  one trigger per object  pattern.","Use a static Boolean variable.","Use a trigger handler.","Use a private Boolean variable."], "answer":["Use a private Boolean variable."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to have records with specific field values in order to test a new Apexclass. What should the developer do to ensure the data is available to the test?", "choice":["Use Test.loadData() and reference a CSV file.","Use SOQL to query the org for the required data.","Use Test.loadData() and reference a static resource.","Use Anonymous Apex to create the required data."], "answer":["Use Test.loadData() and reference a static resource."] , "feedback_tf":["", ""]}
,{ "question":"Which feature allows a developer to create test records for use in test classes?", "choice":["Static resources","Documents","Httpcalloutmocks","Webservicetests"], "answer":["Webservicetests"] , "feedback_tf":["", ""]}
,{ "question":"When the value of a field of an account record is updated, which method will update thevalue of a custom field opportunity? Choose 2 answers.", "choice":["A process builder on the Account object","An Apex trigger on the Account object.","A cross-object formula field on the Account object","A workflow rule on the Account object"], "answer":["A process builder on the Account object","An Apex trigger on the Account object."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to join data received from an integration with an external system withparent records in Salesforce. The data set does not contain the Salesforce IDs of the parent records,but it does have a foreign key attribute that can be used to identify the parent.Which action will allow the developer to relate records in the data model without knowing theSalesforce ID?", "choice":["Create and populate a custom field on the parent object marked as Unique.","Create a custom field on the child object of type External Relationship.","Create and populate a custom field on the parent object marked as an External ID.","Create a custom field on the child object of type Foreign Key."], "answer":["Create a custom field on the child object of type Foreign Key."] , "feedback_tf":["", ""]}
,{ "question":"What is an accurate constructor for a custom controller named  MyController ?", "choice":["public MyController () { account = new Account () ; }","public MyController (sObject obj) { account = (Account) obj; }","public MyController (List objects) { accounts = (List ) objects; }","public MyController (ApexPages.StandardController stdController) { account = (Account)stdController.getRecord(); }"], "answer":["public MyController () { account = new Account () ; }"] , "feedback_tf":["", ""]}
,{ "question":"Which three methods help ensure quality data?", "choice":["Create a lookup filter","Adding an error to a field in before trigger","Sending an email alert using a workflow rule","Handling an exception in Apex","Adding a validation rule"], "answer":["Create a lookup filter","Sending an email alert using a workflow rule","Adding a validation rule"] , "feedback_tf":["", ""]}
,{ "question":"Where would a developer build a managed package?", "choice":["Developer Sandbox","Unlimited Edition","Partial Copy Sandbox","Developer Edition"], "answer":["Developer Edition"] , "feedback_tf":["", ""]}
,{ "question":"A developer can use the debug log to see which three types of information? Choose 3answers", "choice":["Resource usage and limits","Database changes","User login events","HTTP callout to external systems","Actions triggered by time-based workflow"], "answer":["Database changes","HTTP callout to external systems","Actions triggered by time-based workflow"] , "feedback_tf":["", ""]}
]}
