var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"Which three statements are true regarding the @istest annotation? Choose 3 answers", "choice":["Products and pricebooks are visible in a test even if a class is annotated @istest (seealldata=false)","A method annotated @istest (seealldata=false) in a class annotated @istest (seealladata=true) hasaccess to all org data","A method annotated @istest (seealldata=true) in a class annotated @istest (seealladata=false) hasaccess to all org data","Profiles are visible in a test even if a class is annotated @istest (seealldata=false)","A class containing test methods counts toward the apex code liit regardless of any @istest annotation (Missed"], "answer":["A method annotated @istest (seealldata=false) in a class annotated @istest (seealladata=true) hasaccess to all org data","Profiles are visible in a test even if a class is annotated @istest (seealldata=false)","A class containing test methods counts toward the apex code liit regardless of any @istest annotation (Missed"] , "feedback_tf":["", ""]}
,{ "question":"Universal Containers stores Orders and Line Items in Salesforce. For security reason,financial representatives are allowed to see information on the Order such as order amount, but theyare not allowed to see the Line items on the Order. Which type of relationship should be used?", "choice":["Lookup","Direct Lookup","Indirect lookup","Master Detail"], "answer":["Master Detail"] , "feedback_tf":["", ""]}
,{ "question":"Which actions can a developer perform using the Schema Builder?Choose 2 answers", "choice":["Create a custom field and automatically add it to an existing page layout.","Create a view containing only standard and system objects.","Create a custom object and define a lookup relationship on that object","Create a view of objects and relationships without fields"], "answer":["Create a view containing only standard and system objects.","Create a custom object and define a lookup relationship on that object"] , "feedback_tf":["", ""]}
,{ "question":"Which two are best practices when it comes to component and application event handling?Choose 2 answers", "choice":["Handle low-level events in the event handler and re-fire them as higher-level events. (Missed)","Try to use application events as opposed to component events.","Use component events to communicate actions that should be handled at the application level.","Reuse the event logic in a component bundle, by putting the logic in the helper. (Missed)"], "answer":["Handle low-level events in the event handler and re-fire them as higher-level events. (Missed)","Reuse the event logic in a component bundle, by putting the logic in the helper. (Missed)"] , "feedback_tf":["", ""]}
,{ "question":"How should a custom user interface be provided when a user edits an Account in LightningExperience?", "choice":["Override the Account's Edit button with Lightning Flow","Override the Account's Edit button with Lightning Action","Override the Account's Edit button with Lightning page.","Override the Account's Edit button with Lightning component."], "answer":["Override the Account's Edit button with Lightning component."] , "feedback_tf":["", ""]}
,{ "question":"An org has a single account named 'NoContacts' that has no related contacts. Given thequery:List＜Account＞ accounts = [Select ID, (Select ID, Name from Contacts) from Account whereName='NoContacts']; What is the result of running this Apex?", "choice":["accounts[0].contacts is invalid Apex.","accounts[0].contacts is an empty Apex.","accounts[0].contacts is Null.","A QueryException is thrown."], "answer":["accounts[0].contacts is an empty Apex."] , "feedback_tf":["", ""]}
,{ "question":"Which control statement should a developer use to ensure that a loop body executes atleast once?", "choice":["For(variable : list_or_set){}","While (condition){}","For(init_stmt;exit_cond;increment){}","Do {} while (cond)"], "answer":["Do {} while (cond)"] , "feedback_tf":["", ""]}
,{ "question":"The operation manager at a construction company uses a custom object called Machineryto manage the usage and maintenance of its cranes and other machinery. The manager wants to beable to assign machinery to different constructions jobs, and track the dates and costs associatedwith each job. More than one piece of machinery can be assigned to one construction job.What should a developer do to meet these requirements?", "choice":["Create a lookup field on the Construction Job object to the Machinery object.","Create a lookup field on the Machinery object to the Construction Job object.","Create a junction object with Master-Detail Relationship to both the Machinery object and theConstruction Job object.","Create a Master-Detail Lookup on the Machinery object to the Construction Job object."], "answer":["Create a lookup field on the Construction Job object to the Machinery object."] , "feedback_tf":["", ""]}
,{ "question":"A developer needs to prevent the creation of request records when certain conditions existin the system. A RequestLogic class exists to checks the conditions. What is the correctimplementation?", "choice":["Trigger RequestTrigger on Request (after insert) {RequestLogic.validateRecords {trigger.new};}","Trigger RequestTrigger on Request (before insert) {RequestLogic.validateRecords {trigger.new};}","Trigger RequestTrigger on Request (before insert) {if (RequestLogic.isvalid{Request})Request.addError {'Your request cannot be created at this time.'};}","Trigger RequestTrigger on Request (after insert) {if (RequestLogic.isValid{Request})Request.addError {'Your request cannot be created at this time.'};}"], "answer":["Trigger RequestTrigger on Request (before insert) {RequestLogic.validateRecords {trigger.new};}"] , "feedback_tf":["", ""]}
,{ "question":"A Hierarchy Custom Setting stores a specific URL for each profile in Salesforce. Whichstatement can a developer use to retrieve the correct URL for the current user'sprofile and displaythis on a Visualforce Page?", "choice":["{!$Setup.Url_Settings__C.Instance[Profile.Id].URL__c}","{!$Setup.Url_Settings__C.URL__c}","{!$Setup.Url_Settings__C.[Profile.Id].URL__c}","{!$Setup.Url_Settings__C.[$Profile.Id].URL__c}"], "answer":["{!$Setup.Url_Settings__C.URL__c}"] , "feedback_tf":["", ""]}
]}
