var config = {
"settings": {
	"add_css_file":false,
	"add_js_file":false,
	"custom_lang":false,
	"head_write_js":"",
	"head_write_css":"",
	"format":"table",
	"messages":{
		"intro":"Salesforce 認定デベロッパー 練習問題"
	}
},
"questions":[
{ "question":"A developer creates an Apex helper class to handle complex trigger logic. How can thehelper class warn users when the trigger exceeds DML governor limits?", "choice":["By using PageReference.setRedirect() to redirect the user to a custom Visualforce page before thenumber of DML statements is exceeded.","By using Messaging.sendEmail() to continue toe transaction and send an alert to the user after thenumber of DML statements is exceeded.","By using AmexMessage.Messages() to display an error message after the number of DMLstatements is exceeded.","By using Limits.getDMLRows() and then displaying an error message before the number of DMLstatements is exceeded."], "answer":["By using Limits.getDMLRows() and then displaying an error message before the number of DMLstatements is exceeded."] , "feedback_tf":["", ""]}
,{ "question":"Potential home buyers working with a real estate company can make offers on multipleproperties that are listed with the real estate company. Offer amounts can be modified; however, theproperty that has the offer cannot be modified after the offer is placed. What should be done toassociate offers with properties in the schema for the organization?", "choice":["Create a master-detail relationship in the contact object to both the property and offer customobjects","Create a lookup relationship in the property custom object to the offer custom object","Create a master-detail relationship in the offer custom object to the property custom object","Create a lookup relationship in the offer custom object to the property custom object"], "answer":["Create a master-detail relationship in the offer custom object to the property custom object"] , "feedback_tf":["", ""]}
,{ "question":"How many levels of child records can be returned in a single SOQL query from one parentobject?", "choice":["1","3","5","7"], "answer":["1"] , "feedback_tf":["", ""]}
,{ "question":"A developer declared a class as follow.public class wysiwyg { // Properties and methods including DML }Which invocation of a class method will obey the organization-wide defaults and sharing settings forthe running user in the Salesforce Organization?", "choice":["An Apex Trigger that invokes a helper method in this class","A Visualforce page with an Apex controller that invokes a method in this class","A user on an external system that has an API call into Salesforce that invokes a method in this class","A developer using the Developer Console that invokes a method in this class from the executeanonymous window"], "answer":["A developer using the Developer Console that invokes a method in this class from the executeanonymous window"] , "feedback_tf":["", ""]}
,{ "question":"What are three ways for a developer to execute tests in an org? Choose 3.", "choice":["Bulk API","ToolingAPI","Metadata API","Setup Menu"], "answer":["ToolingAPI","Metadata API","Setup Menu"] , "feedback_tf":["", ""]}
,{ "question":"Which two Apex data types can be used to reference a Salesforce record ID dynamically?(Choose two.)", "choice":["ENUM","sObject","External ID","String"], "answer":["ENUM","String"] , "feedback_tf":["", ""]}
,{ "question":"How can a developer determine, from the DescribeSObjectResult, if the current user will beable to create records for an object in Apex?", "choice":["By using the isInsertable() method.","By using the isCreatable() method.","By using the hasAccess() method.","By using the canCreate() method."], "answer":["By using the isCreatable() method."] , "feedback_tf":["", ""]}
,{ "question":"How many level of child records can be returned in a single SOQL query from one parentobject", "choice":["1","3","5","7"], "answer":["1"] , "feedback_tf":["", ""]}
,{ "question":"Which two statements are true about using the @testSetup annotation in an Apex testclass? (Choose two.)", "choice":["The @testSetup annotation cannot be used when the @isTest(SeeAllData=True) annotation isused.","Test data is inserted once for all test methods in a class.","Records created in the @testSetup method cannot be updates in individual test methods.","The @testSetup method is automatically executed before each test method in the test class isexecuted."], "answer":["The @testSetup method is automatically executed before each test method in the test class isexecuted."] , "feedback_tf":["", ""]}
,{ "question":"Where can debug log filter settings be set?Choose 2 answers", "choice":["The Filters link by the monitored user's name within the web UI.","The Show More link on the debug log's record.","On the monitored user's name.","The Log Filters tab on a class or trigger detail page."], "answer":["The Filters link by the monitored user's name within the web UI.","The Log Filters tab on a class or trigger detail page."] , "feedback_tf":["", ""]}
]}
